// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetProductsByIDBundledProductsParams creates a new GetProductsByIDBundledProductsParams object
// with the default values initialized.
func NewGetProductsByIDBundledProductsParams() *GetProductsByIDBundledProductsParams {
	var ()
	return &GetProductsByIDBundledProductsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetProductsByIDBundledProductsParamsWithTimeout creates a new GetProductsByIDBundledProductsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetProductsByIDBundledProductsParamsWithTimeout(timeout time.Duration) *GetProductsByIDBundledProductsParams {
	var ()
	return &GetProductsByIDBundledProductsParams{

		timeout: timeout,
	}
}

// NewGetProductsByIDBundledProductsParamsWithContext creates a new GetProductsByIDBundledProductsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetProductsByIDBundledProductsParamsWithContext(ctx context.Context) *GetProductsByIDBundledProductsParams {
	var ()
	return &GetProductsByIDBundledProductsParams{

		Context: ctx,
	}
}

// NewGetProductsByIDBundledProductsParamsWithHTTPClient creates a new GetProductsByIDBundledProductsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetProductsByIDBundledProductsParamsWithHTTPClient(client *http.Client) *GetProductsByIDBundledProductsParams {
	var ()
	return &GetProductsByIDBundledProductsParams{
		HTTPClient: client,
	}
}

/*GetProductsByIDBundledProductsParams contains all the parameters to send to the API endpoint
for the get products by ID bundled products operation typically these are written to a http.Request
*/
type GetProductsByIDBundledProductsParams struct {

	/*ID
	  The requested product id.

	*/
	ID string
	/*Locale*/
	Locale *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get products by ID bundled products params
func (o *GetProductsByIDBundledProductsParams) WithTimeout(timeout time.Duration) *GetProductsByIDBundledProductsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get products by ID bundled products params
func (o *GetProductsByIDBundledProductsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get products by ID bundled products params
func (o *GetProductsByIDBundledProductsParams) WithContext(ctx context.Context) *GetProductsByIDBundledProductsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get products by ID bundled products params
func (o *GetProductsByIDBundledProductsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get products by ID bundled products params
func (o *GetProductsByIDBundledProductsParams) WithHTTPClient(client *http.Client) *GetProductsByIDBundledProductsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get products by ID bundled products params
func (o *GetProductsByIDBundledProductsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get products by ID bundled products params
func (o *GetProductsByIDBundledProductsParams) WithID(id string) *GetProductsByIDBundledProductsParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get products by ID bundled products params
func (o *GetProductsByIDBundledProductsParams) SetID(id string) {
	o.ID = id
}

// WithLocale adds the locale to the get products by ID bundled products params
func (o *GetProductsByIDBundledProductsParams) WithLocale(locale *string) *GetProductsByIDBundledProductsParams {
	o.SetLocale(locale)
	return o
}

// SetLocale adds the locale to the get products by ID bundled products params
func (o *GetProductsByIDBundledProductsParams) SetLocale(locale *string) {
	o.Locale = locale
}

// WriteToRequest writes these params to a swagger request
func (o *GetProductsByIDBundledProductsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if o.Locale != nil {

		// query param locale
		var qrLocale string
		if o.Locale != nil {
			qrLocale = *o.Locale
		}
		qLocale := qrLocale
		if qLocale != "" {
			if err := r.SetQueryParam("locale", qLocale); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
