// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetProductsByIDVariationsParams creates a new GetProductsByIDVariationsParams object
// with the default values initialized.
func NewGetProductsByIDVariationsParams() *GetProductsByIDVariationsParams {
	var ()
	return &GetProductsByIDVariationsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetProductsByIDVariationsParamsWithTimeout creates a new GetProductsByIDVariationsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetProductsByIDVariationsParamsWithTimeout(timeout time.Duration) *GetProductsByIDVariationsParams {
	var ()
	return &GetProductsByIDVariationsParams{

		timeout: timeout,
	}
}

// NewGetProductsByIDVariationsParamsWithContext creates a new GetProductsByIDVariationsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetProductsByIDVariationsParamsWithContext(ctx context.Context) *GetProductsByIDVariationsParams {
	var ()
	return &GetProductsByIDVariationsParams{

		Context: ctx,
	}
}

// NewGetProductsByIDVariationsParamsWithHTTPClient creates a new GetProductsByIDVariationsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetProductsByIDVariationsParamsWithHTTPClient(client *http.Client) *GetProductsByIDVariationsParams {
	var ()
	return &GetProductsByIDVariationsParams{
		HTTPClient: client,
	}
}

/*GetProductsByIDVariationsParams contains all the parameters to send to the API endpoint
for the get products by ID variations operation typically these are written to a http.Request
*/
type GetProductsByIDVariationsParams struct {

	/*ID
	  The requested product id.

	*/
	ID string
	/*Locale*/
	Locale *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get products by ID variations params
func (o *GetProductsByIDVariationsParams) WithTimeout(timeout time.Duration) *GetProductsByIDVariationsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get products by ID variations params
func (o *GetProductsByIDVariationsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get products by ID variations params
func (o *GetProductsByIDVariationsParams) WithContext(ctx context.Context) *GetProductsByIDVariationsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get products by ID variations params
func (o *GetProductsByIDVariationsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get products by ID variations params
func (o *GetProductsByIDVariationsParams) WithHTTPClient(client *http.Client) *GetProductsByIDVariationsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get products by ID variations params
func (o *GetProductsByIDVariationsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get products by ID variations params
func (o *GetProductsByIDVariationsParams) WithID(id string) *GetProductsByIDVariationsParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get products by ID variations params
func (o *GetProductsByIDVariationsParams) SetID(id string) {
	o.ID = id
}

// WithLocale adds the locale to the get products by ID variations params
func (o *GetProductsByIDVariationsParams) WithLocale(locale *string) *GetProductsByIDVariationsParams {
	o.SetLocale(locale)
	return o
}

// SetLocale adds the locale to the get products by ID variations params
func (o *GetProductsByIDVariationsParams) SetLocale(locale *string) {
	o.Locale = locale
}

// WriteToRequest writes these params to a swagger request
func (o *GetProductsByIDVariationsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if o.Locale != nil {

		// query param locale
		var qrLocale string
		if o.Locale != nil {
			qrLocale = *o.Locale
		}
		qLocale := qrLocale
		if qLocale != "" {
			if err := r.SetQueryParam("locale", qLocale); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
