// Code generated by go-swagger; DO NOT EDIT.

package orders

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetOrdersByIDNotesParams creates a new GetOrdersByIDNotesParams object
// with the default values initialized.
func NewGetOrdersByIDNotesParams() *GetOrdersByIDNotesParams {
	var ()
	return &GetOrdersByIDNotesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetOrdersByIDNotesParamsWithTimeout creates a new GetOrdersByIDNotesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetOrdersByIDNotesParamsWithTimeout(timeout time.Duration) *GetOrdersByIDNotesParams {
	var ()
	return &GetOrdersByIDNotesParams{

		timeout: timeout,
	}
}

// NewGetOrdersByIDNotesParamsWithContext creates a new GetOrdersByIDNotesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetOrdersByIDNotesParamsWithContext(ctx context.Context) *GetOrdersByIDNotesParams {
	var ()
	return &GetOrdersByIDNotesParams{

		Context: ctx,
	}
}

// NewGetOrdersByIDNotesParamsWithHTTPClient creates a new GetOrdersByIDNotesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetOrdersByIDNotesParamsWithHTTPClient(client *http.Client) *GetOrdersByIDNotesParams {
	var ()
	return &GetOrdersByIDNotesParams{
		HTTPClient: client,
	}
}

/*GetOrdersByIDNotesParams contains all the parameters to send to the API endpoint
for the get orders by ID notes operation typically these are written to a http.Request
*/
type GetOrdersByIDNotesParams struct {

	/*OrderNo
	  The id of the order from which you want to retrieve notes.

	*/
	OrderNo string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get orders by ID notes params
func (o *GetOrdersByIDNotesParams) WithTimeout(timeout time.Duration) *GetOrdersByIDNotesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get orders by ID notes params
func (o *GetOrdersByIDNotesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get orders by ID notes params
func (o *GetOrdersByIDNotesParams) WithContext(ctx context.Context) *GetOrdersByIDNotesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get orders by ID notes params
func (o *GetOrdersByIDNotesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get orders by ID notes params
func (o *GetOrdersByIDNotesParams) WithHTTPClient(client *http.Client) *GetOrdersByIDNotesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get orders by ID notes params
func (o *GetOrdersByIDNotesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOrderNo adds the orderNo to the get orders by ID notes params
func (o *GetOrdersByIDNotesParams) WithOrderNo(orderNo string) *GetOrdersByIDNotesParams {
	o.SetOrderNo(orderNo)
	return o
}

// SetOrderNo adds the orderNo to the get orders by ID notes params
func (o *GetOrdersByIDNotesParams) SetOrderNo(orderNo string) {
	o.OrderNo = orderNo
}

// WriteToRequest writes these params to a swagger request
func (o *GetOrdersByIDNotesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param order_no
	if err := r.SetPathParam("order_no", o.OrderNo); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
