// Code generated by go-swagger; DO NOT EDIT.

package custom_object_definitions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetCustomObjectDefinitionsByIDAttributeDefinitionsParams creates a new GetCustomObjectDefinitionsByIDAttributeDefinitionsParams object
// with the default values initialized.
func NewGetCustomObjectDefinitionsByIDAttributeDefinitionsParams() *GetCustomObjectDefinitionsByIDAttributeDefinitionsParams {
	var ()
	return &GetCustomObjectDefinitionsByIDAttributeDefinitionsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetCustomObjectDefinitionsByIDAttributeDefinitionsParamsWithTimeout creates a new GetCustomObjectDefinitionsByIDAttributeDefinitionsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetCustomObjectDefinitionsByIDAttributeDefinitionsParamsWithTimeout(timeout time.Duration) *GetCustomObjectDefinitionsByIDAttributeDefinitionsParams {
	var ()
	return &GetCustomObjectDefinitionsByIDAttributeDefinitionsParams{

		timeout: timeout,
	}
}

// NewGetCustomObjectDefinitionsByIDAttributeDefinitionsParamsWithContext creates a new GetCustomObjectDefinitionsByIDAttributeDefinitionsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetCustomObjectDefinitionsByIDAttributeDefinitionsParamsWithContext(ctx context.Context) *GetCustomObjectDefinitionsByIDAttributeDefinitionsParams {
	var ()
	return &GetCustomObjectDefinitionsByIDAttributeDefinitionsParams{

		Context: ctx,
	}
}

// NewGetCustomObjectDefinitionsByIDAttributeDefinitionsParamsWithHTTPClient creates a new GetCustomObjectDefinitionsByIDAttributeDefinitionsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetCustomObjectDefinitionsByIDAttributeDefinitionsParamsWithHTTPClient(client *http.Client) *GetCustomObjectDefinitionsByIDAttributeDefinitionsParams {
	var ()
	return &GetCustomObjectDefinitionsByIDAttributeDefinitionsParams{
		HTTPClient: client,
	}
}

/*GetCustomObjectDefinitionsByIDAttributeDefinitionsParams contains all the parameters to send to the API endpoint
for the get custom object definitions by ID attribute definitions operation typically these are written to a http.Request
*/
type GetCustomObjectDefinitionsByIDAttributeDefinitionsParams struct {

	/*Count*/
	Count *int32
	/*ObjectType*/
	ObjectType string
	/*Select*/
	Select *string
	/*Start*/
	Start *int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get custom object definitions by ID attribute definitions params
func (o *GetCustomObjectDefinitionsByIDAttributeDefinitionsParams) WithTimeout(timeout time.Duration) *GetCustomObjectDefinitionsByIDAttributeDefinitionsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get custom object definitions by ID attribute definitions params
func (o *GetCustomObjectDefinitionsByIDAttributeDefinitionsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get custom object definitions by ID attribute definitions params
func (o *GetCustomObjectDefinitionsByIDAttributeDefinitionsParams) WithContext(ctx context.Context) *GetCustomObjectDefinitionsByIDAttributeDefinitionsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get custom object definitions by ID attribute definitions params
func (o *GetCustomObjectDefinitionsByIDAttributeDefinitionsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get custom object definitions by ID attribute definitions params
func (o *GetCustomObjectDefinitionsByIDAttributeDefinitionsParams) WithHTTPClient(client *http.Client) *GetCustomObjectDefinitionsByIDAttributeDefinitionsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get custom object definitions by ID attribute definitions params
func (o *GetCustomObjectDefinitionsByIDAttributeDefinitionsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCount adds the count to the get custom object definitions by ID attribute definitions params
func (o *GetCustomObjectDefinitionsByIDAttributeDefinitionsParams) WithCount(count *int32) *GetCustomObjectDefinitionsByIDAttributeDefinitionsParams {
	o.SetCount(count)
	return o
}

// SetCount adds the count to the get custom object definitions by ID attribute definitions params
func (o *GetCustomObjectDefinitionsByIDAttributeDefinitionsParams) SetCount(count *int32) {
	o.Count = count
}

// WithObjectType adds the objectType to the get custom object definitions by ID attribute definitions params
func (o *GetCustomObjectDefinitionsByIDAttributeDefinitionsParams) WithObjectType(objectType string) *GetCustomObjectDefinitionsByIDAttributeDefinitionsParams {
	o.SetObjectType(objectType)
	return o
}

// SetObjectType adds the objectType to the get custom object definitions by ID attribute definitions params
func (o *GetCustomObjectDefinitionsByIDAttributeDefinitionsParams) SetObjectType(objectType string) {
	o.ObjectType = objectType
}

// WithSelect adds the selectVar to the get custom object definitions by ID attribute definitions params
func (o *GetCustomObjectDefinitionsByIDAttributeDefinitionsParams) WithSelect(selectVar *string) *GetCustomObjectDefinitionsByIDAttributeDefinitionsParams {
	o.SetSelect(selectVar)
	return o
}

// SetSelect adds the select to the get custom object definitions by ID attribute definitions params
func (o *GetCustomObjectDefinitionsByIDAttributeDefinitionsParams) SetSelect(selectVar *string) {
	o.Select = selectVar
}

// WithStart adds the start to the get custom object definitions by ID attribute definitions params
func (o *GetCustomObjectDefinitionsByIDAttributeDefinitionsParams) WithStart(start *int32) *GetCustomObjectDefinitionsByIDAttributeDefinitionsParams {
	o.SetStart(start)
	return o
}

// SetStart adds the start to the get custom object definitions by ID attribute definitions params
func (o *GetCustomObjectDefinitionsByIDAttributeDefinitionsParams) SetStart(start *int32) {
	o.Start = start
}

// WriteToRequest writes these params to a swagger request
func (o *GetCustomObjectDefinitionsByIDAttributeDefinitionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Count != nil {

		// query param count
		var qrCount int32
		if o.Count != nil {
			qrCount = *o.Count
		}
		qCount := swag.FormatInt32(qrCount)
		if qCount != "" {
			if err := r.SetQueryParam("count", qCount); err != nil {
				return err
			}
		}

	}

	// path param object_type
	if err := r.SetPathParam("object_type", o.ObjectType); err != nil {
		return err
	}

	if o.Select != nil {

		// query param select
		var qrSelect string
		if o.Select != nil {
			qrSelect = *o.Select
		}
		qSelect := qrSelect
		if qSelect != "" {
			if err := r.SetQueryParam("select", qSelect); err != nil {
				return err
			}
		}

	}

	if o.Start != nil {

		// query param start
		var qrStart int32
		if o.Start != nil {
			qrStart = *o.Start
		}
		qStart := swag.FormatInt32(qrStart)
		if qStart != "" {
			if err := r.SetQueryParam("start", qStart); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
