// Code generated by go-swagger; DO NOT EDIT.

package folders

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetFoldersByIdsParams creates a new GetFoldersByIdsParams object
// with the default values initialized.
func NewGetFoldersByIdsParams() *GetFoldersByIdsParams {
	var ()
	return &GetFoldersByIdsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetFoldersByIdsParamsWithTimeout creates a new GetFoldersByIdsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetFoldersByIdsParamsWithTimeout(timeout time.Duration) *GetFoldersByIdsParams {
	var ()
	return &GetFoldersByIdsParams{

		timeout: timeout,
	}
}

// NewGetFoldersByIdsParamsWithContext creates a new GetFoldersByIdsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetFoldersByIdsParamsWithContext(ctx context.Context) *GetFoldersByIdsParams {
	var ()
	return &GetFoldersByIdsParams{

		Context: ctx,
	}
}

// NewGetFoldersByIdsParamsWithHTTPClient creates a new GetFoldersByIdsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetFoldersByIdsParamsWithHTTPClient(client *http.Client) *GetFoldersByIdsParams {
	var ()
	return &GetFoldersByIdsParams{
		HTTPClient: client,
	}
}

/*GetFoldersByIdsParams contains all the parameters to send to the API endpoint
for the get folders by ids operation typically these are written to a http.Request
*/
type GetFoldersByIdsParams struct {

	/*Ids*/
	Ids []string
	/*Levels*/
	Levels *int32
	/*Locale*/
	Locale *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get folders by ids params
func (o *GetFoldersByIdsParams) WithTimeout(timeout time.Duration) *GetFoldersByIdsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get folders by ids params
func (o *GetFoldersByIdsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get folders by ids params
func (o *GetFoldersByIdsParams) WithContext(ctx context.Context) *GetFoldersByIdsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get folders by ids params
func (o *GetFoldersByIdsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get folders by ids params
func (o *GetFoldersByIdsParams) WithHTTPClient(client *http.Client) *GetFoldersByIdsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get folders by ids params
func (o *GetFoldersByIdsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithIds adds the ids to the get folders by ids params
func (o *GetFoldersByIdsParams) WithIds(ids []string) *GetFoldersByIdsParams {
	o.SetIds(ids)
	return o
}

// SetIds adds the ids to the get folders by ids params
func (o *GetFoldersByIdsParams) SetIds(ids []string) {
	o.Ids = ids
}

// WithLevels adds the levels to the get folders by ids params
func (o *GetFoldersByIdsParams) WithLevels(levels *int32) *GetFoldersByIdsParams {
	o.SetLevels(levels)
	return o
}

// SetLevels adds the levels to the get folders by ids params
func (o *GetFoldersByIdsParams) SetLevels(levels *int32) {
	o.Levels = levels
}

// WithLocale adds the locale to the get folders by ids params
func (o *GetFoldersByIdsParams) WithLocale(locale *string) *GetFoldersByIdsParams {
	o.SetLocale(locale)
	return o
}

// SetLocale adds the locale to the get folders by ids params
func (o *GetFoldersByIdsParams) SetLocale(locale *string) {
	o.Locale = locale
}

// WriteToRequest writes these params to a swagger request
func (o *GetFoldersByIdsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	valuesIds := o.Ids

	joinedIds := swag.JoinByFormat(valuesIds, "")
	// path array param ids
	// SetPathParam does not support variadric arguments, since we used JoinByFormat
	// we can send the first item in the array as it's all the items of the previous
	// array joined together
	if len(joinedIds) > 0 {
		if err := r.SetPathParam("ids", joinedIds[0]); err != nil {
			return err
		}
	}

	if o.Levels != nil {

		// query param levels
		var qrLevels int32
		if o.Levels != nil {
			qrLevels = *o.Levels
		}
		qLevels := swag.FormatInt32(qrLevels)
		if qLevels != "" {
			if err := r.SetQueryParam("levels", qLevels); err != nil {
				return err
			}
		}

	}

	if o.Locale != nil {

		// query param locale
		var qrLocale string
		if o.Locale != nil {
			qrLocale = *o.Locale
		}
		qLocale := qrLocale
		if qLocale != "" {
			if err := r.SetQueryParam("locale", qLocale); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
