// Code generated by go-swagger; DO NOT EDIT.

package user_search

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/intel352/sfcc-ocapi-client/data_api/models"
)

// PostUserSearchReader is a Reader for the PostUserSearch structure.
type PostUserSearchReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostUserSearchReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 400:
		result := NewPostUserSearchBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewPostUserSearchDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPostUserSearchBadRequest creates a PostUserSearchBadRequest with default headers values
func NewPostUserSearchBadRequest() *PostUserSearchBadRequest {
	return &PostUserSearchBadRequest{}
}

/*PostUserSearchBadRequest handles this case with default header values.

Thrown if the query is ill-formed.
*/
type PostUserSearchBadRequest struct {
}

func (o *PostUserSearchBadRequest) Error() string {
	return fmt.Sprintf("[POST /user_search][%d] postUserSearchBadRequest ", 400)
}

func (o *PostUserSearchBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostUserSearchDefault creates a PostUserSearchDefault with default headers values
func NewPostUserSearchDefault(code int) *PostUserSearchDefault {
	return &PostUserSearchDefault{
		_statusCode: code,
	}
}

/*PostUserSearchDefault handles this case with default header values.

PostUserSearchDefault post user search default
*/
type PostUserSearchDefault struct {
	_statusCode int

	Payload *models.UserSearchResult
}

// Code gets the status code for the post user search default response
func (o *PostUserSearchDefault) Code() int {
	return o._statusCode
}

func (o *PostUserSearchDefault) Error() string {
	return fmt.Sprintf("[POST /user_search][%d] postUserSearch default  %+v", o._statusCode, o.Payload)
}

func (o *PostUserSearchDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UserSearchResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
