// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CartridgePathCreateRequest Request Body for put operation
// swagger:model cartridge_path_create_request
type CartridgePathCreateRequest struct {

	// New cartridge path
	// Required: true
	Cartridges *string `json:"cartridges"`
}

// Validate validates this cartridge path create request
func (m *CartridgePathCreateRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCartridges(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CartridgePathCreateRequest) validateCartridges(formats strfmt.Registry) error {

	if err := validate.Required("cartridges", "body", m.Cartridges); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *CartridgePathCreateRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CartridgePathCreateRequest) UnmarshalBinary(b []byte) error {
	var res CartridgePathCreateRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
