// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CategoryProductAssignmentSearchRequest Document representing product_search_request
// swagger:model category_product_assignment_search_request
type CategoryProductAssignmentSearchRequest struct {

	// The number of returned documents.
	// Maximum: 200
	// Minimum: 1
	Count int32 `json:"count,omitempty"`

	// The zero-based index of the record that we want to start with, used to optimize special handling
	// Minimum: 0
	DbStartRecord *int32 `json:"db_start_record_,omitempty"`

	// The list of expansions that can be applied:
	//
	//  product_base - String - This expand will enable retrieval of the following basic Product information:
	//
	//  		brand
	//     	ean
	//       link
	//   	long_description
	//       manufacturer_name
	//       manufacturer_sku
	//  		name
	//       page_description
	//       page_keywords
	//       page_title
	//       searchable
	//    	short_description
	//       type
	//       unit
	//      	upc
	//
	//
	Expand []string `json:"expand"`

	// The query passed into the search
	// Required: true
	Query Query `json:"query"`

	// The fields that you want to select.
	Select string `json:"select,omitempty"`

	// The list of sort clauses configured for the search request. Sort clauses are optional.
	Sorts []*Sort `json:"sorts"`

	// The zero-based index of the first search hit to include in the result.
	// Minimum: 0
	Start *int32 `json:"start,omitempty"`
}

// Validate validates this category product assignment search request
func (m *CategoryProductAssignmentSearchRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCount(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDbStartRecord(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateQuery(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSorts(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStart(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CategoryProductAssignmentSearchRequest) validateCount(formats strfmt.Registry) error {

	if swag.IsZero(m.Count) { // not required
		return nil
	}

	if err := validate.MinimumInt("count", "body", int64(m.Count), 1, false); err != nil {
		return err
	}

	if err := validate.MaximumInt("count", "body", int64(m.Count), 200, false); err != nil {
		return err
	}

	return nil
}

func (m *CategoryProductAssignmentSearchRequest) validateDbStartRecord(formats strfmt.Registry) error {

	if swag.IsZero(m.DbStartRecord) { // not required
		return nil
	}

	if err := validate.MinimumInt("db_start_record_", "body", int64(*m.DbStartRecord), 0, false); err != nil {
		return err
	}

	return nil
}

func (m *CategoryProductAssignmentSearchRequest) validateQuery(formats strfmt.Registry) error {

	if err := validate.Required("query", "body", m.Query); err != nil {
		return err
	}

	return nil
}

func (m *CategoryProductAssignmentSearchRequest) validateSorts(formats strfmt.Registry) error {

	if swag.IsZero(m.Sorts) { // not required
		return nil
	}

	for i := 0; i < len(m.Sorts); i++ {
		if swag.IsZero(m.Sorts[i]) { // not required
			continue
		}

		if m.Sorts[i] != nil {
			if err := m.Sorts[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("sorts" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *CategoryProductAssignmentSearchRequest) validateStart(formats strfmt.Registry) error {

	if swag.IsZero(m.Start) { // not required
		return nil
	}

	if err := validate.MinimumInt("start", "body", int64(*m.Start), 0, false); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *CategoryProductAssignmentSearchRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CategoryProductAssignmentSearchRequest) UnmarshalBinary(b []byte) error {
	var res CategoryProductAssignmentSearchRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
