// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// FunctionalPermission Document representing a functional permission.
// swagger:model functional_permission
type FunctionalPermission struct {

	// The description of the functional permission.
	Description map[string]string `json:"description,omitempty"`

	// The display name of the functional permission.
	DisplayName map[string]string `json:"display_name,omitempty"`

	// The name of the functional permission.
	Name string `json:"name,omitempty"`

	// The permission type.
	Type string `json:"type,omitempty"`

	// The list of possible values for the functional permission, e.g. ACCESS or READONLY.
	Values []string `json:"values"`
}

// Validate validates this functional permission
func (m *FunctionalPermission) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *FunctionalPermission) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *FunctionalPermission) UnmarshalBinary(b []byte) error {
	var res FunctionalPermission
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
