// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Master master
// swagger:model master
type Master struct {

	// link
	// Required: true
	// Min Length: 1
	Link *string `json:"link"`

	// master id
	// Required: true
	// Max Length: 100
	// Min Length: 1
	MasterID *string `json:"master_id"`

	// orderable
	Orderable bool `json:"orderable,omitempty"`

	// price
	Price float64 `json:"price,omitempty"`

	// price max
	PriceMax float64 `json:"price_max,omitempty"`

	// prices
	Prices map[string]float64 `json:"prices,omitempty"`
}

// Validate validates this master
func (m *Master) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLink(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMasterID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Master) validateLink(formats strfmt.Registry) error {

	if err := validate.Required("link", "body", m.Link); err != nil {
		return err
	}

	if err := validate.MinLength("link", "body", string(*m.Link), 1); err != nil {
		return err
	}

	return nil
}

func (m *Master) validateMasterID(formats strfmt.Registry) error {

	if err := validate.Required("master_id", "body", m.MasterID); err != nil {
		return err
	}

	if err := validate.MinLength("master_id", "body", string(*m.MasterID), 1); err != nil {
		return err
	}

	if err := validate.MaxLength("master_id", "body", string(*m.MasterID), 100); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Master) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Master) UnmarshalBinary(b []byte) error {
	var res Master
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
