// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SortingRuleStep Document representing a product sorting rule step
// swagger:model sorting_rule_step
type SortingRuleStep struct {

	// the id for sorting attribute.
	AttributeID string `json:"attribute_id,omitempty"`

	// the direction of the sorting attribute
	// Enum: [asc desc]
	Direction string `json:"direction,omitempty"`

	// whether or not the attribute is a system attribute.
	IsSystem bool `json:"is_system,omitempty"`

	// the position of product sorting rule step.
	Position int32 `json:"position,omitempty"`

	// The text relevance included.
	TextRelevanceIncluded bool `json:"text_relevance_included,omitempty"`

	// the sorting type for sorting attribute.
	TypeID string `json:"type_id,omitempty"`
}

// Validate validates this sorting rule step
func (m *SortingRuleStep) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDirection(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var sortingRuleStepTypeDirectionPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["asc","desc"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		sortingRuleStepTypeDirectionPropEnum = append(sortingRuleStepTypeDirectionPropEnum, v)
	}
}

const (

	// SortingRuleStepDirectionAsc captures enum value "asc"
	SortingRuleStepDirectionAsc string = "asc"

	// SortingRuleStepDirectionDesc captures enum value "desc"
	SortingRuleStepDirectionDesc string = "desc"
)

// prop value enum
func (m *SortingRuleStep) validateDirectionEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, sortingRuleStepTypeDirectionPropEnum); err != nil {
		return err
	}
	return nil
}

func (m *SortingRuleStep) validateDirection(formats strfmt.Registry) error {

	if swag.IsZero(m.Direction) { // not required
		return nil
	}

	// value enum
	if err := m.validateDirectionEnum("direction", "body", m.Direction); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *SortingRuleStep) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SortingRuleStep) UnmarshalBinary(b []byte) error {
	var res SortingRuleStep
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
