// Code generated by go-swagger; DO NOT EDIT.

package baskets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteBasketsByIDShipmentsByIDParams creates a new DeleteBasketsByIDShipmentsByIDParams object
// with the default values initialized.
func NewDeleteBasketsByIDShipmentsByIDParams() *DeleteBasketsByIDShipmentsByIDParams {
	var ()
	return &DeleteBasketsByIDShipmentsByIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteBasketsByIDShipmentsByIDParamsWithTimeout creates a new DeleteBasketsByIDShipmentsByIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteBasketsByIDShipmentsByIDParamsWithTimeout(timeout time.Duration) *DeleteBasketsByIDShipmentsByIDParams {
	var ()
	return &DeleteBasketsByIDShipmentsByIDParams{

		timeout: timeout,
	}
}

// NewDeleteBasketsByIDShipmentsByIDParamsWithContext creates a new DeleteBasketsByIDShipmentsByIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteBasketsByIDShipmentsByIDParamsWithContext(ctx context.Context) *DeleteBasketsByIDShipmentsByIDParams {
	var ()
	return &DeleteBasketsByIDShipmentsByIDParams{

		Context: ctx,
	}
}

// NewDeleteBasketsByIDShipmentsByIDParamsWithHTTPClient creates a new DeleteBasketsByIDShipmentsByIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteBasketsByIDShipmentsByIDParamsWithHTTPClient(client *http.Client) *DeleteBasketsByIDShipmentsByIDParams {
	var ()
	return &DeleteBasketsByIDShipmentsByIDParams{
		HTTPClient: client,
	}
}

/*DeleteBasketsByIDShipmentsByIDParams contains all the parameters to send to the API endpoint
for the delete baskets by ID shipments by ID operation typically these are written to a http.Request
*/
type DeleteBasketsByIDShipmentsByIDParams struct {

	/*BasketID
	  the id of the basket to be modified

	*/
	BasketID string
	/*ShipmentID
	  the id of the shipment to be deleted

	*/
	ShipmentID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete baskets by ID shipments by ID params
func (o *DeleteBasketsByIDShipmentsByIDParams) WithTimeout(timeout time.Duration) *DeleteBasketsByIDShipmentsByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete baskets by ID shipments by ID params
func (o *DeleteBasketsByIDShipmentsByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete baskets by ID shipments by ID params
func (o *DeleteBasketsByIDShipmentsByIDParams) WithContext(ctx context.Context) *DeleteBasketsByIDShipmentsByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete baskets by ID shipments by ID params
func (o *DeleteBasketsByIDShipmentsByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete baskets by ID shipments by ID params
func (o *DeleteBasketsByIDShipmentsByIDParams) WithHTTPClient(client *http.Client) *DeleteBasketsByIDShipmentsByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete baskets by ID shipments by ID params
func (o *DeleteBasketsByIDShipmentsByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBasketID adds the basketID to the delete baskets by ID shipments by ID params
func (o *DeleteBasketsByIDShipmentsByIDParams) WithBasketID(basketID string) *DeleteBasketsByIDShipmentsByIDParams {
	o.SetBasketID(basketID)
	return o
}

// SetBasketID adds the basketId to the delete baskets by ID shipments by ID params
func (o *DeleteBasketsByIDShipmentsByIDParams) SetBasketID(basketID string) {
	o.BasketID = basketID
}

// WithShipmentID adds the shipmentID to the delete baskets by ID shipments by ID params
func (o *DeleteBasketsByIDShipmentsByIDParams) WithShipmentID(shipmentID string) *DeleteBasketsByIDShipmentsByIDParams {
	o.SetShipmentID(shipmentID)
	return o
}

// SetShipmentID adds the shipmentId to the delete baskets by ID shipments by ID params
func (o *DeleteBasketsByIDShipmentsByIDParams) SetShipmentID(shipmentID string) {
	o.ShipmentID = shipmentID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteBasketsByIDShipmentsByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param basket_id
	if err := r.SetPathParam("basket_id", o.BasketID); err != nil {
		return err
	}

	// path param shipment_id
	if err := r.SetPathParam("shipment_id", o.ShipmentID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
