// Code generated by go-swagger; DO NOT EDIT.

package baskets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/intel352/sfcc-ocapi-client/shop_api/models"
)

// PostBasketsByIDNotesReader is a Reader for the PostBasketsByIDNotes structure.
type PostBasketsByIDNotesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostBasketsByIDNotesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 404:
		result := NewPostBasketsByIDNotesNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewPostBasketsByIDNotesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPostBasketsByIDNotesNotFound creates a PostBasketsByIDNotesNotFound with default headers values
func NewPostBasketsByIDNotesNotFound() *PostBasketsByIDNotesNotFound {
	return &PostBasketsByIDNotesNotFound{}
}

/*PostBasketsByIDNotesNotFound handles this case with default header values.

Indicates that the basket with the given basket id is unknown.
*/
type PostBasketsByIDNotesNotFound struct {
}

func (o *PostBasketsByIDNotesNotFound) Error() string {
	return fmt.Sprintf("[POST /baskets/{basket_id}/notes][%d] postBasketsByIdNotesNotFound ", 404)
}

func (o *PostBasketsByIDNotesNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostBasketsByIDNotesDefault creates a PostBasketsByIDNotesDefault with default headers values
func NewPostBasketsByIDNotesDefault(code int) *PostBasketsByIDNotesDefault {
	return &PostBasketsByIDNotesDefault{
		_statusCode: code,
	}
}

/*PostBasketsByIDNotesDefault handles this case with default header values.

PostBasketsByIDNotesDefault post baskets by ID notes default
*/
type PostBasketsByIDNotesDefault struct {
	_statusCode int

	Payload *models.Basket
}

// Code gets the status code for the post baskets by ID notes default response
func (o *PostBasketsByIDNotesDefault) Code() int {
	return o._statusCode
}

func (o *PostBasketsByIDNotesDefault) Error() string {
	return fmt.Sprintf("[POST /baskets/{basket_id}/notes][%d] postBasketsByIDNotes default  %+v", o._statusCode, o.Payload)
}

func (o *PostBasketsByIDNotesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Basket)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
