// Code generated by go-swagger; DO NOT EDIT.

package permissions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/intel352/sfcc-ocapi-client/data_api/models"
)

// GetPermissionsBmModuleReader is a Reader for the GetPermissionsBmModule structure.
type GetPermissionsBmModuleReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPermissionsBmModuleReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {

	result := NewGetPermissionsBmModuleDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result

}

// NewGetPermissionsBmModuleDefault creates a GetPermissionsBmModuleDefault with default headers values
func NewGetPermissionsBmModuleDefault(code int) *GetPermissionsBmModuleDefault {
	return &GetPermissionsBmModuleDefault{
		_statusCode: code,
	}
}

/*GetPermissionsBmModuleDefault handles this case with default header values.

GetPermissionsBmModuleDefault get permissions bm module default
*/
type GetPermissionsBmModuleDefault struct {
	_statusCode int

	Payload *models.ModulePermissions
}

// Code gets the status code for the get permissions bm module default response
func (o *GetPermissionsBmModuleDefault) Code() int {
	return o._statusCode
}

func (o *GetPermissionsBmModuleDefault) Error() string {
	return fmt.Sprintf("[GET /permissions/bm/module][%d] getPermissionsBmModule default  %+v", o._statusCode, o.Payload)
}

func (o *GetPermissionsBmModuleDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ModulePermissions)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
