// Code generated by go-swagger; DO NOT EDIT.

package sites

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteSitesByIDStoresByIDReader is a Reader for the DeleteSitesByIDStoresByID structure.
type DeleteSitesByIDStoresByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteSitesByIDStoresByIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewDeleteSitesByIDStoresByIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 404:
		result := NewDeleteSitesByIDStoresByIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteSitesByIDStoresByIDNoContent creates a DeleteSitesByIDStoresByIDNoContent with default headers values
func NewDeleteSitesByIDStoresByIDNoContent() *DeleteSitesByIDStoresByIDNoContent {
	return &DeleteSitesByIDStoresByIDNoContent{}
}

/*DeleteSitesByIDStoresByIDNoContent handles this case with default header values.

DeleteSitesByIDStoresByIDNoContent delete sites by Id stores by Id no content
*/
type DeleteSitesByIDStoresByIDNoContent struct {
}

func (o *DeleteSitesByIDStoresByIDNoContent) Error() string {
	return fmt.Sprintf("[DELETE /sites/{site_id}/stores/{id}][%d] deleteSitesByIdStoresByIdNoContent ", 204)
}

func (o *DeleteSitesByIDStoresByIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteSitesByIDStoresByIDNotFound creates a DeleteSitesByIDStoresByIDNotFound with default headers values
func NewDeleteSitesByIDStoresByIDNotFound() *DeleteSitesByIDStoresByIDNotFound {
	return &DeleteSitesByIDStoresByIDNotFound{}
}

/*DeleteSitesByIDStoresByIDNotFound handles this case with default header values.

Thrown in case the store does not exist matching the given id
*/
type DeleteSitesByIDStoresByIDNotFound struct {
}

func (o *DeleteSitesByIDStoresByIDNotFound) Error() string {
	return fmt.Sprintf("[DELETE /sites/{site_id}/stores/{id}][%d] deleteSitesByIdStoresByIdNotFound ", 404)
}

func (o *DeleteSitesByIDStoresByIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
