// Code generated by go-swagger; DO NOT EDIT.

package sites

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetSitesByIDCustomerGroupsByIDMembersByIDParams creates a new GetSitesByIDCustomerGroupsByIDMembersByIDParams object
// with the default values initialized.
func NewGetSitesByIDCustomerGroupsByIDMembersByIDParams() *GetSitesByIDCustomerGroupsByIDMembersByIDParams {
	var ()
	return &GetSitesByIDCustomerGroupsByIDMembersByIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetSitesByIDCustomerGroupsByIDMembersByIDParamsWithTimeout creates a new GetSitesByIDCustomerGroupsByIDMembersByIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetSitesByIDCustomerGroupsByIDMembersByIDParamsWithTimeout(timeout time.Duration) *GetSitesByIDCustomerGroupsByIDMembersByIDParams {
	var ()
	return &GetSitesByIDCustomerGroupsByIDMembersByIDParams{

		timeout: timeout,
	}
}

// NewGetSitesByIDCustomerGroupsByIDMembersByIDParamsWithContext creates a new GetSitesByIDCustomerGroupsByIDMembersByIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetSitesByIDCustomerGroupsByIDMembersByIDParamsWithContext(ctx context.Context) *GetSitesByIDCustomerGroupsByIDMembersByIDParams {
	var ()
	return &GetSitesByIDCustomerGroupsByIDMembersByIDParams{

		Context: ctx,
	}
}

// NewGetSitesByIDCustomerGroupsByIDMembersByIDParamsWithHTTPClient creates a new GetSitesByIDCustomerGroupsByIDMembersByIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetSitesByIDCustomerGroupsByIDMembersByIDParamsWithHTTPClient(client *http.Client) *GetSitesByIDCustomerGroupsByIDMembersByIDParams {
	var ()
	return &GetSitesByIDCustomerGroupsByIDMembersByIDParams{
		HTTPClient: client,
	}
}

/*GetSitesByIDCustomerGroupsByIDMembersByIDParams contains all the parameters to send to the API endpoint
for the get sites by ID customer groups by ID members by ID operation typically these are written to a http.Request
*/
type GetSitesByIDCustomerGroupsByIDMembersByIDParams struct {

	/*CustomerNo
	  The customer number of the requested customer group member.

	*/
	CustomerNo string
	/*ID
	  The id of the requested members customer group.

	*/
	ID string
	/*Select*/
	Select *string
	/*SiteID
	  The id of the site.

	*/
	SiteID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get sites by ID customer groups by ID members by ID params
func (o *GetSitesByIDCustomerGroupsByIDMembersByIDParams) WithTimeout(timeout time.Duration) *GetSitesByIDCustomerGroupsByIDMembersByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get sites by ID customer groups by ID members by ID params
func (o *GetSitesByIDCustomerGroupsByIDMembersByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get sites by ID customer groups by ID members by ID params
func (o *GetSitesByIDCustomerGroupsByIDMembersByIDParams) WithContext(ctx context.Context) *GetSitesByIDCustomerGroupsByIDMembersByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get sites by ID customer groups by ID members by ID params
func (o *GetSitesByIDCustomerGroupsByIDMembersByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get sites by ID customer groups by ID members by ID params
func (o *GetSitesByIDCustomerGroupsByIDMembersByIDParams) WithHTTPClient(client *http.Client) *GetSitesByIDCustomerGroupsByIDMembersByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get sites by ID customer groups by ID members by ID params
func (o *GetSitesByIDCustomerGroupsByIDMembersByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCustomerNo adds the customerNo to the get sites by ID customer groups by ID members by ID params
func (o *GetSitesByIDCustomerGroupsByIDMembersByIDParams) WithCustomerNo(customerNo string) *GetSitesByIDCustomerGroupsByIDMembersByIDParams {
	o.SetCustomerNo(customerNo)
	return o
}

// SetCustomerNo adds the customerNo to the get sites by ID customer groups by ID members by ID params
func (o *GetSitesByIDCustomerGroupsByIDMembersByIDParams) SetCustomerNo(customerNo string) {
	o.CustomerNo = customerNo
}

// WithID adds the id to the get sites by ID customer groups by ID members by ID params
func (o *GetSitesByIDCustomerGroupsByIDMembersByIDParams) WithID(id string) *GetSitesByIDCustomerGroupsByIDMembersByIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get sites by ID customer groups by ID members by ID params
func (o *GetSitesByIDCustomerGroupsByIDMembersByIDParams) SetID(id string) {
	o.ID = id
}

// WithSelect adds the selectVar to the get sites by ID customer groups by ID members by ID params
func (o *GetSitesByIDCustomerGroupsByIDMembersByIDParams) WithSelect(selectVar *string) *GetSitesByIDCustomerGroupsByIDMembersByIDParams {
	o.SetSelect(selectVar)
	return o
}

// SetSelect adds the select to the get sites by ID customer groups by ID members by ID params
func (o *GetSitesByIDCustomerGroupsByIDMembersByIDParams) SetSelect(selectVar *string) {
	o.Select = selectVar
}

// WithSiteID adds the siteID to the get sites by ID customer groups by ID members by ID params
func (o *GetSitesByIDCustomerGroupsByIDMembersByIDParams) WithSiteID(siteID string) *GetSitesByIDCustomerGroupsByIDMembersByIDParams {
	o.SetSiteID(siteID)
	return o
}

// SetSiteID adds the siteId to the get sites by ID customer groups by ID members by ID params
func (o *GetSitesByIDCustomerGroupsByIDMembersByIDParams) SetSiteID(siteID string) {
	o.SiteID = siteID
}

// WriteToRequest writes these params to a swagger request
func (o *GetSitesByIDCustomerGroupsByIDMembersByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param customer_no
	if err := r.SetPathParam("customer_no", o.CustomerNo); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if o.Select != nil {

		// query param select
		var qrSelect string
		if o.Select != nil {
			qrSelect = *o.Select
		}
		qSelect := qrSelect
		if qSelect != "" {
			if err := r.SetQueryParam("select", qSelect); err != nil {
				return err
			}
		}

	}

	// path param site_id
	if err := r.SetPathParam("site_id", o.SiteID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
