// Code generated by go-swagger; DO NOT EDIT.

package sites

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetSitesByIDAbTestsByIDParams creates a new GetSitesByIDAbTestsByIDParams object
// with the default values initialized.
func NewGetSitesByIDAbTestsByIDParams() *GetSitesByIDAbTestsByIDParams {
	var ()
	return &GetSitesByIDAbTestsByIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetSitesByIDAbTestsByIDParamsWithTimeout creates a new GetSitesByIDAbTestsByIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetSitesByIDAbTestsByIDParamsWithTimeout(timeout time.Duration) *GetSitesByIDAbTestsByIDParams {
	var ()
	return &GetSitesByIDAbTestsByIDParams{

		timeout: timeout,
	}
}

// NewGetSitesByIDAbTestsByIDParamsWithContext creates a new GetSitesByIDAbTestsByIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetSitesByIDAbTestsByIDParamsWithContext(ctx context.Context) *GetSitesByIDAbTestsByIDParams {
	var ()
	return &GetSitesByIDAbTestsByIDParams{

		Context: ctx,
	}
}

// NewGetSitesByIDAbTestsByIDParamsWithHTTPClient creates a new GetSitesByIDAbTestsByIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetSitesByIDAbTestsByIDParamsWithHTTPClient(client *http.Client) *GetSitesByIDAbTestsByIDParams {
	var ()
	return &GetSitesByIDAbTestsByIDParams{
		HTTPClient: client,
	}
}

/*GetSitesByIDAbTestsByIDParams contains all the parameters to send to the API endpoint
for the get sites by ID ab tests by ID operation typically these are written to a http.Request
*/
type GetSitesByIDAbTestsByIDParams struct {

	/*Expand*/
	Expand []string
	/*ID
	  The id of the requested A/B Test.

	*/
	ID string
	/*SiteID
	  ID of the site that the A/B tests are contained within.

	*/
	SiteID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get sites by ID ab tests by ID params
func (o *GetSitesByIDAbTestsByIDParams) WithTimeout(timeout time.Duration) *GetSitesByIDAbTestsByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get sites by ID ab tests by ID params
func (o *GetSitesByIDAbTestsByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get sites by ID ab tests by ID params
func (o *GetSitesByIDAbTestsByIDParams) WithContext(ctx context.Context) *GetSitesByIDAbTestsByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get sites by ID ab tests by ID params
func (o *GetSitesByIDAbTestsByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get sites by ID ab tests by ID params
func (o *GetSitesByIDAbTestsByIDParams) WithHTTPClient(client *http.Client) *GetSitesByIDAbTestsByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get sites by ID ab tests by ID params
func (o *GetSitesByIDAbTestsByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithExpand adds the expand to the get sites by ID ab tests by ID params
func (o *GetSitesByIDAbTestsByIDParams) WithExpand(expand []string) *GetSitesByIDAbTestsByIDParams {
	o.SetExpand(expand)
	return o
}

// SetExpand adds the expand to the get sites by ID ab tests by ID params
func (o *GetSitesByIDAbTestsByIDParams) SetExpand(expand []string) {
	o.Expand = expand
}

// WithID adds the id to the get sites by ID ab tests by ID params
func (o *GetSitesByIDAbTestsByIDParams) WithID(id string) *GetSitesByIDAbTestsByIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get sites by ID ab tests by ID params
func (o *GetSitesByIDAbTestsByIDParams) SetID(id string) {
	o.ID = id
}

// WithSiteID adds the siteID to the get sites by ID ab tests by ID params
func (o *GetSitesByIDAbTestsByIDParams) WithSiteID(siteID string) *GetSitesByIDAbTestsByIDParams {
	o.SetSiteID(siteID)
	return o
}

// SetSiteID adds the siteId to the get sites by ID ab tests by ID params
func (o *GetSitesByIDAbTestsByIDParams) SetSiteID(siteID string) {
	o.SiteID = siteID
}

// WriteToRequest writes these params to a swagger request
func (o *GetSitesByIDAbTestsByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	valuesExpand := o.Expand

	joinedExpand := swag.JoinByFormat(valuesExpand, "")
	// query array param expand
	if err := r.SetQueryParam("expand", joinedExpand...); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	// path param site_id
	if err := r.SetPathParam("site_id", o.SiteID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
