// Code generated by go-swagger; DO NOT EDIT.

package sites

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/intel352/sfcc-ocapi-client/data_api/models"
)

// GetSitesByIDAbTestsByIDReader is a Reader for the GetSitesByIDAbTestsByID structure.
type GetSitesByIDAbTestsByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetSitesByIDAbTestsByIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 404:
		result := NewGetSitesByIDAbTestsByIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewGetSitesByIDAbTestsByIDDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetSitesByIDAbTestsByIDNotFound creates a GetSitesByIDAbTestsByIDNotFound with default headers values
func NewGetSitesByIDAbTestsByIDNotFound() *GetSitesByIDAbTestsByIDNotFound {
	return &GetSitesByIDAbTestsByIDNotFound{}
}

/*GetSitesByIDAbTestsByIDNotFound handles this case with default header values.

Indicates that site specified with the given id is unknown. or Thrown in case the A/B Test does not exist matching the given id
*/
type GetSitesByIDAbTestsByIDNotFound struct {
}

func (o *GetSitesByIDAbTestsByIDNotFound) Error() string {
	return fmt.Sprintf("[GET /sites/{site_id}/ab_tests/{id}][%d] getSitesByIdAbTestsByIdNotFound ", 404)
}

func (o *GetSitesByIDAbTestsByIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetSitesByIDAbTestsByIDDefault creates a GetSitesByIDAbTestsByIDDefault with default headers values
func NewGetSitesByIDAbTestsByIDDefault(code int) *GetSitesByIDAbTestsByIDDefault {
	return &GetSitesByIDAbTestsByIDDefault{
		_statusCode: code,
	}
}

/*GetSitesByIDAbTestsByIDDefault handles this case with default header values.

GetSitesByIDAbTestsByIDDefault get sites by ID ab tests by ID default
*/
type GetSitesByIDAbTestsByIDDefault struct {
	_statusCode int

	Payload *models.AbTest
}

// Code gets the status code for the get sites by ID ab tests by ID default response
func (o *GetSitesByIDAbTestsByIDDefault) Code() int {
	return o._statusCode
}

func (o *GetSitesByIDAbTestsByIDDefault) Error() string {
	return fmt.Sprintf("[GET /sites/{site_id}/ab_tests/{id}][%d] getSitesByIDAbTestsByID default  %+v", o._statusCode, o.Payload)
}

func (o *GetSitesByIDAbTestsByIDDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AbTest)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
