// Code generated by go-swagger; DO NOT EDIT.

package sites

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/intel352/sfcc-ocapi-client/data_api/models"
)

// NewPatchSitesByIDSlotsByIDSlotConfigurationsByIDParams creates a new PatchSitesByIDSlotsByIDSlotConfigurationsByIDParams object
// with the default values initialized.
func NewPatchSitesByIDSlotsByIDSlotConfigurationsByIDParams() *PatchSitesByIDSlotsByIDSlotConfigurationsByIDParams {
	var ()
	return &PatchSitesByIDSlotsByIDSlotConfigurationsByIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPatchSitesByIDSlotsByIDSlotConfigurationsByIDParamsWithTimeout creates a new PatchSitesByIDSlotsByIDSlotConfigurationsByIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPatchSitesByIDSlotsByIDSlotConfigurationsByIDParamsWithTimeout(timeout time.Duration) *PatchSitesByIDSlotsByIDSlotConfigurationsByIDParams {
	var ()
	return &PatchSitesByIDSlotsByIDSlotConfigurationsByIDParams{

		timeout: timeout,
	}
}

// NewPatchSitesByIDSlotsByIDSlotConfigurationsByIDParamsWithContext creates a new PatchSitesByIDSlotsByIDSlotConfigurationsByIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewPatchSitesByIDSlotsByIDSlotConfigurationsByIDParamsWithContext(ctx context.Context) *PatchSitesByIDSlotsByIDSlotConfigurationsByIDParams {
	var ()
	return &PatchSitesByIDSlotsByIDSlotConfigurationsByIDParams{

		Context: ctx,
	}
}

// NewPatchSitesByIDSlotsByIDSlotConfigurationsByIDParamsWithHTTPClient creates a new PatchSitesByIDSlotsByIDSlotConfigurationsByIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPatchSitesByIDSlotsByIDSlotConfigurationsByIDParamsWithHTTPClient(client *http.Client) *PatchSitesByIDSlotsByIDSlotConfigurationsByIDParams {
	var ()
	return &PatchSitesByIDSlotsByIDSlotConfigurationsByIDParams{
		HTTPClient: client,
	}
}

/*PatchSitesByIDSlotsByIDSlotConfigurationsByIDParams contains all the parameters to send to the API endpoint
for the patch sites by ID slots by ID slot configurations by ID operation typically these are written to a http.Request
*/
type PatchSitesByIDSlotsByIDSlotConfigurationsByIDParams struct {

	/*Body*/
	Body *models.SlotConfiguration
	/*ConfigurationID
	  The id of the slot configuration.

	*/
	ConfigurationID string
	/*Context*/
	Context *string
	/*SiteID
	  The id of the site for which you want to create the slot configuration.

	*/
	SiteID string
	/*SlotID
	  The id of the slot.

	*/
	SlotID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the patch sites by ID slots by ID slot configurations by ID params
func (o *PatchSitesByIDSlotsByIDSlotConfigurationsByIDParams) WithTimeout(timeout time.Duration) *PatchSitesByIDSlotsByIDSlotConfigurationsByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patch sites by ID slots by ID slot configurations by ID params
func (o *PatchSitesByIDSlotsByIDSlotConfigurationsByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the patch sites by ID slots by ID slot configurations by ID params
func (o *PatchSitesByIDSlotsByIDSlotConfigurationsByIDParams) WithContext(ctx context.Context) *PatchSitesByIDSlotsByIDSlotConfigurationsByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patch sites by ID slots by ID slot configurations by ID params
func (o *PatchSitesByIDSlotsByIDSlotConfigurationsByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patch sites by ID slots by ID slot configurations by ID params
func (o *PatchSitesByIDSlotsByIDSlotConfigurationsByIDParams) WithHTTPClient(client *http.Client) *PatchSitesByIDSlotsByIDSlotConfigurationsByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patch sites by ID slots by ID slot configurations by ID params
func (o *PatchSitesByIDSlotsByIDSlotConfigurationsByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the patch sites by ID slots by ID slot configurations by ID params
func (o *PatchSitesByIDSlotsByIDSlotConfigurationsByIDParams) WithBody(body *models.SlotConfiguration) *PatchSitesByIDSlotsByIDSlotConfigurationsByIDParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the patch sites by ID slots by ID slot configurations by ID params
func (o *PatchSitesByIDSlotsByIDSlotConfigurationsByIDParams) SetBody(body *models.SlotConfiguration) {
	o.Body = body
}

// WithConfigurationID adds the configurationID to the patch sites by ID slots by ID slot configurations by ID params
func (o *PatchSitesByIDSlotsByIDSlotConfigurationsByIDParams) WithConfigurationID(configurationID string) *PatchSitesByIDSlotsByIDSlotConfigurationsByIDParams {
	o.SetConfigurationID(configurationID)
	return o
}

// SetConfigurationID adds the configurationId to the patch sites by ID slots by ID slot configurations by ID params
func (o *PatchSitesByIDSlotsByIDSlotConfigurationsByIDParams) SetConfigurationID(configurationID string) {
	o.ConfigurationID = configurationID
}

// WithContext adds the context to the patch sites by ID slots by ID slot configurations by ID params
func (o *PatchSitesByIDSlotsByIDSlotConfigurationsByIDParams) WithContext(context *string) *PatchSitesByIDSlotsByIDSlotConfigurationsByIDParams {
	o.SetContext(context)
	return o
}

// SetContext adds the context to the patch sites by ID slots by ID slot configurations by ID params
func (o *PatchSitesByIDSlotsByIDSlotConfigurationsByIDParams) SetContext(context *string) {
	o.Context = context
}

// WithSiteID adds the siteID to the patch sites by ID slots by ID slot configurations by ID params
func (o *PatchSitesByIDSlotsByIDSlotConfigurationsByIDParams) WithSiteID(siteID string) *PatchSitesByIDSlotsByIDSlotConfigurationsByIDParams {
	o.SetSiteID(siteID)
	return o
}

// SetSiteID adds the siteId to the patch sites by ID slots by ID slot configurations by ID params
func (o *PatchSitesByIDSlotsByIDSlotConfigurationsByIDParams) SetSiteID(siteID string) {
	o.SiteID = siteID
}

// WithSlotID adds the slotID to the patch sites by ID slots by ID slot configurations by ID params
func (o *PatchSitesByIDSlotsByIDSlotConfigurationsByIDParams) WithSlotID(slotID string) *PatchSitesByIDSlotsByIDSlotConfigurationsByIDParams {
	o.SetSlotID(slotID)
	return o
}

// SetSlotID adds the slotId to the patch sites by ID slots by ID slot configurations by ID params
func (o *PatchSitesByIDSlotsByIDSlotConfigurationsByIDParams) SetSlotID(slotID string) {
	o.SlotID = slotID
}

// WriteToRequest writes these params to a swagger request
func (o *PatchSitesByIDSlotsByIDSlotConfigurationsByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param configuration_id
	if err := r.SetPathParam("configuration_id", o.ConfigurationID); err != nil {
		return err
	}

	if o.Context != nil {

		// query param context
		var qrContext string
		if o.Context != nil {
			qrContext = *o.Context
		}
		qContext := qrContext
		if qContext != "" {
			if err := r.SetQueryParam("context", qContext); err != nil {
				return err
			}
		}

	}

	// path param site_id
	if err := r.SetPathParam("site_id", o.SiteID); err != nil {
		return err
	}

	// path param slot_id
	if err := r.SetPathParam("slot_id", o.SlotID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
