// Code generated by go-swagger; DO NOT EDIT.

package sites

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/intel352/sfcc-ocapi-client/data_api/models"
)

// PostSitesByIDPromotionCampaignAssignmentSearchReader is a Reader for the PostSitesByIDPromotionCampaignAssignmentSearch structure.
type PostSitesByIDPromotionCampaignAssignmentSearchReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostSitesByIDPromotionCampaignAssignmentSearchReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {

	result := NewPostSitesByIDPromotionCampaignAssignmentSearchDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result

}

// NewPostSitesByIDPromotionCampaignAssignmentSearchDefault creates a PostSitesByIDPromotionCampaignAssignmentSearchDefault with default headers values
func NewPostSitesByIDPromotionCampaignAssignmentSearchDefault(code int) *PostSitesByIDPromotionCampaignAssignmentSearchDefault {
	return &PostSitesByIDPromotionCampaignAssignmentSearchDefault{
		_statusCode: code,
	}
}

/*PostSitesByIDPromotionCampaignAssignmentSearchDefault handles this case with default header values.

PostSitesByIDPromotionCampaignAssignmentSearchDefault post sites by ID promotion campaign assignment search default
*/
type PostSitesByIDPromotionCampaignAssignmentSearchDefault struct {
	_statusCode int

	Payload *models.PromotionCampaignAssignmentSearchResult
}

// Code gets the status code for the post sites by ID promotion campaign assignment search default response
func (o *PostSitesByIDPromotionCampaignAssignmentSearchDefault) Code() int {
	return o._statusCode
}

func (o *PostSitesByIDPromotionCampaignAssignmentSearchDefault) Error() string {
	return fmt.Sprintf("[POST /sites/{site_id}/promotion_campaign_assignment_search][%d] postSitesByIDPromotionCampaignAssignmentSearch default  %+v", o._statusCode, o.Payload)
}

func (o *PostSitesByIDPromotionCampaignAssignmentSearchDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PromotionCampaignAssignmentSearchResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
