// Code generated by go-swagger; DO NOT EDIT.

package sites

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/intel352/sfcc-ocapi-client/data_api/models"
)

// NewPostSitesByIDSlotConfigurationCampaignAssignmentSearchParams creates a new PostSitesByIDSlotConfigurationCampaignAssignmentSearchParams object
// with the default values initialized.
func NewPostSitesByIDSlotConfigurationCampaignAssignmentSearchParams() *PostSitesByIDSlotConfigurationCampaignAssignmentSearchParams {
	var ()
	return &PostSitesByIDSlotConfigurationCampaignAssignmentSearchParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostSitesByIDSlotConfigurationCampaignAssignmentSearchParamsWithTimeout creates a new PostSitesByIDSlotConfigurationCampaignAssignmentSearchParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostSitesByIDSlotConfigurationCampaignAssignmentSearchParamsWithTimeout(timeout time.Duration) *PostSitesByIDSlotConfigurationCampaignAssignmentSearchParams {
	var ()
	return &PostSitesByIDSlotConfigurationCampaignAssignmentSearchParams{

		timeout: timeout,
	}
}

// NewPostSitesByIDSlotConfigurationCampaignAssignmentSearchParamsWithContext creates a new PostSitesByIDSlotConfigurationCampaignAssignmentSearchParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostSitesByIDSlotConfigurationCampaignAssignmentSearchParamsWithContext(ctx context.Context) *PostSitesByIDSlotConfigurationCampaignAssignmentSearchParams {
	var ()
	return &PostSitesByIDSlotConfigurationCampaignAssignmentSearchParams{

		Context: ctx,
	}
}

// NewPostSitesByIDSlotConfigurationCampaignAssignmentSearchParamsWithHTTPClient creates a new PostSitesByIDSlotConfigurationCampaignAssignmentSearchParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostSitesByIDSlotConfigurationCampaignAssignmentSearchParamsWithHTTPClient(client *http.Client) *PostSitesByIDSlotConfigurationCampaignAssignmentSearchParams {
	var ()
	return &PostSitesByIDSlotConfigurationCampaignAssignmentSearchParams{
		HTTPClient: client,
	}
}

/*PostSitesByIDSlotConfigurationCampaignAssignmentSearchParams contains all the parameters to send to the API endpoint
for the post sites by ID slot configuration campaign assignment search operation typically these are written to a http.Request
*/
type PostSitesByIDSlotConfigurationCampaignAssignmentSearchParams struct {

	/*Body*/
	Body *models.SearchRequest
	/*SiteID
	  The site context.

	*/
	SiteID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post sites by ID slot configuration campaign assignment search params
func (o *PostSitesByIDSlotConfigurationCampaignAssignmentSearchParams) WithTimeout(timeout time.Duration) *PostSitesByIDSlotConfigurationCampaignAssignmentSearchParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post sites by ID slot configuration campaign assignment search params
func (o *PostSitesByIDSlotConfigurationCampaignAssignmentSearchParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post sites by ID slot configuration campaign assignment search params
func (o *PostSitesByIDSlotConfigurationCampaignAssignmentSearchParams) WithContext(ctx context.Context) *PostSitesByIDSlotConfigurationCampaignAssignmentSearchParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post sites by ID slot configuration campaign assignment search params
func (o *PostSitesByIDSlotConfigurationCampaignAssignmentSearchParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post sites by ID slot configuration campaign assignment search params
func (o *PostSitesByIDSlotConfigurationCampaignAssignmentSearchParams) WithHTTPClient(client *http.Client) *PostSitesByIDSlotConfigurationCampaignAssignmentSearchParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post sites by ID slot configuration campaign assignment search params
func (o *PostSitesByIDSlotConfigurationCampaignAssignmentSearchParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post sites by ID slot configuration campaign assignment search params
func (o *PostSitesByIDSlotConfigurationCampaignAssignmentSearchParams) WithBody(body *models.SearchRequest) *PostSitesByIDSlotConfigurationCampaignAssignmentSearchParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post sites by ID slot configuration campaign assignment search params
func (o *PostSitesByIDSlotConfigurationCampaignAssignmentSearchParams) SetBody(body *models.SearchRequest) {
	o.Body = body
}

// WithSiteID adds the siteID to the post sites by ID slot configuration campaign assignment search params
func (o *PostSitesByIDSlotConfigurationCampaignAssignmentSearchParams) WithSiteID(siteID string) *PostSitesByIDSlotConfigurationCampaignAssignmentSearchParams {
	o.SetSiteID(siteID)
	return o
}

// SetSiteID adds the siteId to the post sites by ID slot configuration campaign assignment search params
func (o *PostSitesByIDSlotConfigurationCampaignAssignmentSearchParams) SetSiteID(siteID string) {
	o.SiteID = siteID
}

// WriteToRequest writes these params to a swagger request
func (o *PostSitesByIDSlotConfigurationCampaignAssignmentSearchParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param site_id
	if err := r.SetPathParam("site_id", o.SiteID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
