// Code generated by go-swagger; DO NOT EDIT.

package sites

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PutSitesByIDCampaignsByIDCustomerGroupsByIDReader is a Reader for the PutSitesByIDCampaignsByIDCustomerGroupsByID structure.
type PutSitesByIDCampaignsByIDCustomerGroupsByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutSitesByIDCampaignsByIDCustomerGroupsByIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewPutSitesByIDCampaignsByIDCustomerGroupsByIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewPutSitesByIDCampaignsByIDCustomerGroupsByIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewPutSitesByIDCampaignsByIDCustomerGroupsByIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPutSitesByIDCampaignsByIDCustomerGroupsByIDNoContent creates a PutSitesByIDCampaignsByIDCustomerGroupsByIDNoContent with default headers values
func NewPutSitesByIDCampaignsByIDCustomerGroupsByIDNoContent() *PutSitesByIDCampaignsByIDCustomerGroupsByIDNoContent {
	return &PutSitesByIDCampaignsByIDCustomerGroupsByIDNoContent{}
}

/*PutSitesByIDCampaignsByIDCustomerGroupsByIDNoContent handles this case with default header values.

PutSitesByIDCampaignsByIDCustomerGroupsByIDNoContent put sites by Id campaigns by Id customer groups by Id no content
*/
type PutSitesByIDCampaignsByIDCustomerGroupsByIDNoContent struct {
}

func (o *PutSitesByIDCampaignsByIDCustomerGroupsByIDNoContent) Error() string {
	return fmt.Sprintf("[PUT /sites/{site_id}/campaigns/{campaign_id}/customer_groups/{customer_group_id}][%d] putSitesByIdCampaignsByIdCustomerGroupsByIdNoContent ", 204)
}

func (o *PutSitesByIDCampaignsByIDCustomerGroupsByIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPutSitesByIDCampaignsByIDCustomerGroupsByIDBadRequest creates a PutSitesByIDCampaignsByIDCustomerGroupsByIDBadRequest with default headers values
func NewPutSitesByIDCampaignsByIDCustomerGroupsByIDBadRequest() *PutSitesByIDCampaignsByIDCustomerGroupsByIDBadRequest {
	return &PutSitesByIDCampaignsByIDCustomerGroupsByIDBadRequest{}
}

/*PutSitesByIDCampaignsByIDCustomerGroupsByIDBadRequest handles this case with default header values.

Indicates some parameter constraint violation occurs
*/
type PutSitesByIDCampaignsByIDCustomerGroupsByIDBadRequest struct {
}

func (o *PutSitesByIDCampaignsByIDCustomerGroupsByIDBadRequest) Error() string {
	return fmt.Sprintf("[PUT /sites/{site_id}/campaigns/{campaign_id}/customer_groups/{customer_group_id}][%d] putSitesByIdCampaignsByIdCustomerGroupsByIdBadRequest ", 400)
}

func (o *PutSitesByIDCampaignsByIDCustomerGroupsByIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPutSitesByIDCampaignsByIDCustomerGroupsByIDNotFound creates a PutSitesByIDCampaignsByIDCustomerGroupsByIDNotFound with default headers values
func NewPutSitesByIDCampaignsByIDCustomerGroupsByIDNotFound() *PutSitesByIDCampaignsByIDCustomerGroupsByIDNotFound {
	return &PutSitesByIDCampaignsByIDCustomerGroupsByIDNotFound{}
}

/*PutSitesByIDCampaignsByIDCustomerGroupsByIDNotFound handles this case with default header values.

Indicates that the campaign with the given campaign id
              is unknown.
*/
type PutSitesByIDCampaignsByIDCustomerGroupsByIDNotFound struct {
}

func (o *PutSitesByIDCampaignsByIDCustomerGroupsByIDNotFound) Error() string {
	return fmt.Sprintf("[PUT /sites/{site_id}/campaigns/{campaign_id}/customer_groups/{customer_group_id}][%d] putSitesByIdCampaignsByIdCustomerGroupsByIdNotFound ", 404)
}

func (o *PutSitesByIDCampaignsByIDCustomerGroupsByIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
