// Code generated by go-swagger; DO NOT EDIT.

package sites

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/intel352/sfcc-ocapi-client/data_api/models"
)

// NewPutSitesByIDCustomObjectsByIDByIDParams creates a new PutSitesByIDCustomObjectsByIDByIDParams object
// with the default values initialized.
func NewPutSitesByIDCustomObjectsByIDByIDParams() *PutSitesByIDCustomObjectsByIDByIDParams {
	var ()
	return &PutSitesByIDCustomObjectsByIDByIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutSitesByIDCustomObjectsByIDByIDParamsWithTimeout creates a new PutSitesByIDCustomObjectsByIDByIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutSitesByIDCustomObjectsByIDByIDParamsWithTimeout(timeout time.Duration) *PutSitesByIDCustomObjectsByIDByIDParams {
	var ()
	return &PutSitesByIDCustomObjectsByIDByIDParams{

		timeout: timeout,
	}
}

// NewPutSitesByIDCustomObjectsByIDByIDParamsWithContext creates a new PutSitesByIDCustomObjectsByIDByIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutSitesByIDCustomObjectsByIDByIDParamsWithContext(ctx context.Context) *PutSitesByIDCustomObjectsByIDByIDParams {
	var ()
	return &PutSitesByIDCustomObjectsByIDByIDParams{

		Context: ctx,
	}
}

// NewPutSitesByIDCustomObjectsByIDByIDParamsWithHTTPClient creates a new PutSitesByIDCustomObjectsByIDByIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutSitesByIDCustomObjectsByIDByIDParamsWithHTTPClient(client *http.Client) *PutSitesByIDCustomObjectsByIDByIDParams {
	var ()
	return &PutSitesByIDCustomObjectsByIDByIDParams{
		HTTPClient: client,
	}
}

/*PutSitesByIDCustomObjectsByIDByIDParams contains all the parameters to send to the API endpoint
for the put sites by ID custom objects by ID by ID operation typically these are written to a http.Request
*/
type PutSitesByIDCustomObjectsByIDByIDParams struct {

	/*Body*/
	Body *models.CustomObject
	/*Key
	  the key attribute value of the Custom Object

	*/
	Key string
	/*ObjectType
	  the ID of the object type

	*/
	ObjectType string
	/*SiteID
	  the ID of the site

	*/
	SiteID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put sites by ID custom objects by ID by ID params
func (o *PutSitesByIDCustomObjectsByIDByIDParams) WithTimeout(timeout time.Duration) *PutSitesByIDCustomObjectsByIDByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put sites by ID custom objects by ID by ID params
func (o *PutSitesByIDCustomObjectsByIDByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put sites by ID custom objects by ID by ID params
func (o *PutSitesByIDCustomObjectsByIDByIDParams) WithContext(ctx context.Context) *PutSitesByIDCustomObjectsByIDByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put sites by ID custom objects by ID by ID params
func (o *PutSitesByIDCustomObjectsByIDByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put sites by ID custom objects by ID by ID params
func (o *PutSitesByIDCustomObjectsByIDByIDParams) WithHTTPClient(client *http.Client) *PutSitesByIDCustomObjectsByIDByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put sites by ID custom objects by ID by ID params
func (o *PutSitesByIDCustomObjectsByIDByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the put sites by ID custom objects by ID by ID params
func (o *PutSitesByIDCustomObjectsByIDByIDParams) WithBody(body *models.CustomObject) *PutSitesByIDCustomObjectsByIDByIDParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the put sites by ID custom objects by ID by ID params
func (o *PutSitesByIDCustomObjectsByIDByIDParams) SetBody(body *models.CustomObject) {
	o.Body = body
}

// WithKey adds the key to the put sites by ID custom objects by ID by ID params
func (o *PutSitesByIDCustomObjectsByIDByIDParams) WithKey(key string) *PutSitesByIDCustomObjectsByIDByIDParams {
	o.SetKey(key)
	return o
}

// SetKey adds the key to the put sites by ID custom objects by ID by ID params
func (o *PutSitesByIDCustomObjectsByIDByIDParams) SetKey(key string) {
	o.Key = key
}

// WithObjectType adds the objectType to the put sites by ID custom objects by ID by ID params
func (o *PutSitesByIDCustomObjectsByIDByIDParams) WithObjectType(objectType string) *PutSitesByIDCustomObjectsByIDByIDParams {
	o.SetObjectType(objectType)
	return o
}

// SetObjectType adds the objectType to the put sites by ID custom objects by ID by ID params
func (o *PutSitesByIDCustomObjectsByIDByIDParams) SetObjectType(objectType string) {
	o.ObjectType = objectType
}

// WithSiteID adds the siteID to the put sites by ID custom objects by ID by ID params
func (o *PutSitesByIDCustomObjectsByIDByIDParams) WithSiteID(siteID string) *PutSitesByIDCustomObjectsByIDByIDParams {
	o.SetSiteID(siteID)
	return o
}

// SetSiteID adds the siteId to the put sites by ID custom objects by ID by ID params
func (o *PutSitesByIDCustomObjectsByIDByIDParams) SetSiteID(siteID string) {
	o.SiteID = siteID
}

// WriteToRequest writes these params to a swagger request
func (o *PutSitesByIDCustomObjectsByIDByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param key
	if err := r.SetPathParam("key", o.Key); err != nil {
		return err
	}

	// path param object_type
	if err := r.SetPathParam("object_type", o.ObjectType); err != nil {
		return err
	}

	// path param site_id
	if err := r.SetPathParam("site_id", o.SiteID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
