// Code generated by go-swagger; DO NOT EDIT.

package sites

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/intel352/sfcc-ocapi-client/data_api/models"
)

// PutSitesByIDAbTestsByIDSegmentsByIDReader is a Reader for the PutSitesByIDAbTestsByIDSegmentsByID structure.
type PutSitesByIDAbTestsByIDSegmentsByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutSitesByIDAbTestsByIDSegmentsByIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 404:
		result := NewPutSitesByIDAbTestsByIDSegmentsByIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewPutSitesByIDAbTestsByIDSegmentsByIDDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPutSitesByIDAbTestsByIDSegmentsByIDNotFound creates a PutSitesByIDAbTestsByIDSegmentsByIDNotFound with default headers values
func NewPutSitesByIDAbTestsByIDSegmentsByIDNotFound() *PutSitesByIDAbTestsByIDSegmentsByIDNotFound {
	return &PutSitesByIDAbTestsByIDSegmentsByIDNotFound{}
}

/*PutSitesByIDAbTestsByIDSegmentsByIDNotFound handles this case with default header values.

Indicates that site specified with the given id is unknown. or Thrown in case the A/B Test does not exist matching the given id or Thrown if the segment cannot be found in the A/B Test provided
*/
type PutSitesByIDAbTestsByIDSegmentsByIDNotFound struct {
}

func (o *PutSitesByIDAbTestsByIDSegmentsByIDNotFound) Error() string {
	return fmt.Sprintf("[PUT /sites/{site_id}/ab_tests/{id}/segments/{segment_id}][%d] putSitesByIdAbTestsByIdSegmentsByIdNotFound ", 404)
}

func (o *PutSitesByIDAbTestsByIDSegmentsByIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPutSitesByIDAbTestsByIDSegmentsByIDDefault creates a PutSitesByIDAbTestsByIDSegmentsByIDDefault with default headers values
func NewPutSitesByIDAbTestsByIDSegmentsByIDDefault(code int) *PutSitesByIDAbTestsByIDSegmentsByIDDefault {
	return &PutSitesByIDAbTestsByIDSegmentsByIDDefault{
		_statusCode: code,
	}
}

/*PutSitesByIDAbTestsByIDSegmentsByIDDefault handles this case with default header values.

PutSitesByIDAbTestsByIDSegmentsByIDDefault put sites by ID ab tests by ID segments by ID default
*/
type PutSitesByIDAbTestsByIDSegmentsByIDDefault struct {
	_statusCode int

	Payload *models.AbTestSegment
}

// Code gets the status code for the put sites by ID ab tests by ID segments by ID default response
func (o *PutSitesByIDAbTestsByIDSegmentsByIDDefault) Code() int {
	return o._statusCode
}

func (o *PutSitesByIDAbTestsByIDSegmentsByIDDefault) Error() string {
	return fmt.Sprintf("[PUT /sites/{site_id}/ab_tests/{id}/segments/{segment_id}][%d] putSitesByIDAbTestsByIDSegmentsByID default  %+v", o._statusCode, o.Payload)
}

func (o *PutSitesByIDAbTestsByIDSegmentsByIDDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AbTestSegment)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
