// Code generated by go-swagger; DO NOT EDIT.

package catalogs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteCatalogsByIDCategoriesByIDReader is a Reader for the DeleteCatalogsByIDCategoriesByID structure.
type DeleteCatalogsByIDCategoriesByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteCatalogsByIDCategoriesByIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewDeleteCatalogsByIDCategoriesByIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 404:
		result := NewDeleteCatalogsByIDCategoriesByIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteCatalogsByIDCategoriesByIDNoContent creates a DeleteCatalogsByIDCategoriesByIDNoContent with default headers values
func NewDeleteCatalogsByIDCategoriesByIDNoContent() *DeleteCatalogsByIDCategoriesByIDNoContent {
	return &DeleteCatalogsByIDCategoriesByIDNoContent{}
}

/*DeleteCatalogsByIDCategoriesByIDNoContent handles this case with default header values.

DeleteCatalogsByIDCategoriesByIDNoContent delete catalogs by Id categories by Id no content
*/
type DeleteCatalogsByIDCategoriesByIDNoContent struct {
}

func (o *DeleteCatalogsByIDCategoriesByIDNoContent) Error() string {
	return fmt.Sprintf("[DELETE /catalogs/{catalog_id}/categories/{category_id}][%d] deleteCatalogsByIdCategoriesByIdNoContent ", 204)
}

func (o *DeleteCatalogsByIDCategoriesByIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteCatalogsByIDCategoriesByIDNotFound creates a DeleteCatalogsByIDCategoriesByIDNotFound with default headers values
func NewDeleteCatalogsByIDCategoriesByIDNotFound() *DeleteCatalogsByIDCategoriesByIDNotFound {
	return &DeleteCatalogsByIDCategoriesByIDNotFound{}
}

/*DeleteCatalogsByIDCategoriesByIDNotFound handles this case with default header values.

Indicates that the catalog is not provided in the request. or Indicates that the category does not exist for the catalog provided in
              the request.
*/
type DeleteCatalogsByIDCategoriesByIDNotFound struct {
}

func (o *DeleteCatalogsByIDCategoriesByIDNotFound) Error() string {
	return fmt.Sprintf("[DELETE /catalogs/{catalog_id}/categories/{category_id}][%d] deleteCatalogsByIdCategoriesByIdNotFound ", 404)
}

func (o *DeleteCatalogsByIDCategoriesByIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
