// Code generated by go-swagger; DO NOT EDIT.

package catalogs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteCatalogsByIDSharedProductOptionsByIDParams creates a new DeleteCatalogsByIDSharedProductOptionsByIDParams object
// with the default values initialized.
func NewDeleteCatalogsByIDSharedProductOptionsByIDParams() *DeleteCatalogsByIDSharedProductOptionsByIDParams {
	var ()
	return &DeleteCatalogsByIDSharedProductOptionsByIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteCatalogsByIDSharedProductOptionsByIDParamsWithTimeout creates a new DeleteCatalogsByIDSharedProductOptionsByIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteCatalogsByIDSharedProductOptionsByIDParamsWithTimeout(timeout time.Duration) *DeleteCatalogsByIDSharedProductOptionsByIDParams {
	var ()
	return &DeleteCatalogsByIDSharedProductOptionsByIDParams{

		timeout: timeout,
	}
}

// NewDeleteCatalogsByIDSharedProductOptionsByIDParamsWithContext creates a new DeleteCatalogsByIDSharedProductOptionsByIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteCatalogsByIDSharedProductOptionsByIDParamsWithContext(ctx context.Context) *DeleteCatalogsByIDSharedProductOptionsByIDParams {
	var ()
	return &DeleteCatalogsByIDSharedProductOptionsByIDParams{

		Context: ctx,
	}
}

// NewDeleteCatalogsByIDSharedProductOptionsByIDParamsWithHTTPClient creates a new DeleteCatalogsByIDSharedProductOptionsByIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteCatalogsByIDSharedProductOptionsByIDParamsWithHTTPClient(client *http.Client) *DeleteCatalogsByIDSharedProductOptionsByIDParams {
	var ()
	return &DeleteCatalogsByIDSharedProductOptionsByIDParams{
		HTTPClient: client,
	}
}

/*DeleteCatalogsByIDSharedProductOptionsByIDParams contains all the parameters to send to the API endpoint
for the delete catalogs by ID shared product options by ID operation typically these are written to a http.Request
*/
type DeleteCatalogsByIDSharedProductOptionsByIDParams struct {

	/*CatalogID
	  The id of the catalog.

	*/
	CatalogID string
	/*ID
	  The id of the shared product option.

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete catalogs by ID shared product options by ID params
func (o *DeleteCatalogsByIDSharedProductOptionsByIDParams) WithTimeout(timeout time.Duration) *DeleteCatalogsByIDSharedProductOptionsByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete catalogs by ID shared product options by ID params
func (o *DeleteCatalogsByIDSharedProductOptionsByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete catalogs by ID shared product options by ID params
func (o *DeleteCatalogsByIDSharedProductOptionsByIDParams) WithContext(ctx context.Context) *DeleteCatalogsByIDSharedProductOptionsByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete catalogs by ID shared product options by ID params
func (o *DeleteCatalogsByIDSharedProductOptionsByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete catalogs by ID shared product options by ID params
func (o *DeleteCatalogsByIDSharedProductOptionsByIDParams) WithHTTPClient(client *http.Client) *DeleteCatalogsByIDSharedProductOptionsByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete catalogs by ID shared product options by ID params
func (o *DeleteCatalogsByIDSharedProductOptionsByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCatalogID adds the catalogID to the delete catalogs by ID shared product options by ID params
func (o *DeleteCatalogsByIDSharedProductOptionsByIDParams) WithCatalogID(catalogID string) *DeleteCatalogsByIDSharedProductOptionsByIDParams {
	o.SetCatalogID(catalogID)
	return o
}

// SetCatalogID adds the catalogId to the delete catalogs by ID shared product options by ID params
func (o *DeleteCatalogsByIDSharedProductOptionsByIDParams) SetCatalogID(catalogID string) {
	o.CatalogID = catalogID
}

// WithID adds the id to the delete catalogs by ID shared product options by ID params
func (o *DeleteCatalogsByIDSharedProductOptionsByIDParams) WithID(id string) *DeleteCatalogsByIDSharedProductOptionsByIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete catalogs by ID shared product options by ID params
func (o *DeleteCatalogsByIDSharedProductOptionsByIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteCatalogsByIDSharedProductOptionsByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param catalog_id
	if err := r.SetPathParam("catalog_id", o.CatalogID); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
