// Code generated by go-swagger; DO NOT EDIT.

package catalogs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteCatalogsByIDSharedVariationAttributesByIDValuesByIDParams creates a new DeleteCatalogsByIDSharedVariationAttributesByIDValuesByIDParams object
// with the default values initialized.
func NewDeleteCatalogsByIDSharedVariationAttributesByIDValuesByIDParams() *DeleteCatalogsByIDSharedVariationAttributesByIDValuesByIDParams {
	var ()
	return &DeleteCatalogsByIDSharedVariationAttributesByIDValuesByIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteCatalogsByIDSharedVariationAttributesByIDValuesByIDParamsWithTimeout creates a new DeleteCatalogsByIDSharedVariationAttributesByIDValuesByIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteCatalogsByIDSharedVariationAttributesByIDValuesByIDParamsWithTimeout(timeout time.Duration) *DeleteCatalogsByIDSharedVariationAttributesByIDValuesByIDParams {
	var ()
	return &DeleteCatalogsByIDSharedVariationAttributesByIDValuesByIDParams{

		timeout: timeout,
	}
}

// NewDeleteCatalogsByIDSharedVariationAttributesByIDValuesByIDParamsWithContext creates a new DeleteCatalogsByIDSharedVariationAttributesByIDValuesByIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteCatalogsByIDSharedVariationAttributesByIDValuesByIDParamsWithContext(ctx context.Context) *DeleteCatalogsByIDSharedVariationAttributesByIDValuesByIDParams {
	var ()
	return &DeleteCatalogsByIDSharedVariationAttributesByIDValuesByIDParams{

		Context: ctx,
	}
}

// NewDeleteCatalogsByIDSharedVariationAttributesByIDValuesByIDParamsWithHTTPClient creates a new DeleteCatalogsByIDSharedVariationAttributesByIDValuesByIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteCatalogsByIDSharedVariationAttributesByIDValuesByIDParamsWithHTTPClient(client *http.Client) *DeleteCatalogsByIDSharedVariationAttributesByIDValuesByIDParams {
	var ()
	return &DeleteCatalogsByIDSharedVariationAttributesByIDValuesByIDParams{
		HTTPClient: client,
	}
}

/*DeleteCatalogsByIDSharedVariationAttributesByIDValuesByIDParams contains all the parameters to send to the API endpoint
for the delete catalogs by ID shared variation attributes by ID values by ID operation typically these are written to a http.Request
*/
type DeleteCatalogsByIDSharedVariationAttributesByIDValuesByIDParams struct {

	/*AttributeID
	  The id of the variation attribute that contains the value.

	*/
	AttributeID string
	/*CatalogID
	  The id of the catalog.

	*/
	CatalogID string
	/*ID
	  The id of one value to remove

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete catalogs by ID shared variation attributes by ID values by ID params
func (o *DeleteCatalogsByIDSharedVariationAttributesByIDValuesByIDParams) WithTimeout(timeout time.Duration) *DeleteCatalogsByIDSharedVariationAttributesByIDValuesByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete catalogs by ID shared variation attributes by ID values by ID params
func (o *DeleteCatalogsByIDSharedVariationAttributesByIDValuesByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete catalogs by ID shared variation attributes by ID values by ID params
func (o *DeleteCatalogsByIDSharedVariationAttributesByIDValuesByIDParams) WithContext(ctx context.Context) *DeleteCatalogsByIDSharedVariationAttributesByIDValuesByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete catalogs by ID shared variation attributes by ID values by ID params
func (o *DeleteCatalogsByIDSharedVariationAttributesByIDValuesByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete catalogs by ID shared variation attributes by ID values by ID params
func (o *DeleteCatalogsByIDSharedVariationAttributesByIDValuesByIDParams) WithHTTPClient(client *http.Client) *DeleteCatalogsByIDSharedVariationAttributesByIDValuesByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete catalogs by ID shared variation attributes by ID values by ID params
func (o *DeleteCatalogsByIDSharedVariationAttributesByIDValuesByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAttributeID adds the attributeID to the delete catalogs by ID shared variation attributes by ID values by ID params
func (o *DeleteCatalogsByIDSharedVariationAttributesByIDValuesByIDParams) WithAttributeID(attributeID string) *DeleteCatalogsByIDSharedVariationAttributesByIDValuesByIDParams {
	o.SetAttributeID(attributeID)
	return o
}

// SetAttributeID adds the attributeId to the delete catalogs by ID shared variation attributes by ID values by ID params
func (o *DeleteCatalogsByIDSharedVariationAttributesByIDValuesByIDParams) SetAttributeID(attributeID string) {
	o.AttributeID = attributeID
}

// WithCatalogID adds the catalogID to the delete catalogs by ID shared variation attributes by ID values by ID params
func (o *DeleteCatalogsByIDSharedVariationAttributesByIDValuesByIDParams) WithCatalogID(catalogID string) *DeleteCatalogsByIDSharedVariationAttributesByIDValuesByIDParams {
	o.SetCatalogID(catalogID)
	return o
}

// SetCatalogID adds the catalogId to the delete catalogs by ID shared variation attributes by ID values by ID params
func (o *DeleteCatalogsByIDSharedVariationAttributesByIDValuesByIDParams) SetCatalogID(catalogID string) {
	o.CatalogID = catalogID
}

// WithID adds the id to the delete catalogs by ID shared variation attributes by ID values by ID params
func (o *DeleteCatalogsByIDSharedVariationAttributesByIDValuesByIDParams) WithID(id string) *DeleteCatalogsByIDSharedVariationAttributesByIDValuesByIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete catalogs by ID shared variation attributes by ID values by ID params
func (o *DeleteCatalogsByIDSharedVariationAttributesByIDValuesByIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteCatalogsByIDSharedVariationAttributesByIDValuesByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param attribute_id
	if err := r.SetPathParam("attribute_id", o.AttributeID); err != nil {
		return err
	}

	// path param catalog_id
	if err := r.SetPathParam("catalog_id", o.CatalogID); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
