// Code generated by go-swagger; DO NOT EDIT.

package catalogs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetCatalogsByIDSharedVariationAttributesByIDParams creates a new GetCatalogsByIDSharedVariationAttributesByIDParams object
// with the default values initialized.
func NewGetCatalogsByIDSharedVariationAttributesByIDParams() *GetCatalogsByIDSharedVariationAttributesByIDParams {
	var ()
	return &GetCatalogsByIDSharedVariationAttributesByIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetCatalogsByIDSharedVariationAttributesByIDParamsWithTimeout creates a new GetCatalogsByIDSharedVariationAttributesByIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetCatalogsByIDSharedVariationAttributesByIDParamsWithTimeout(timeout time.Duration) *GetCatalogsByIDSharedVariationAttributesByIDParams {
	var ()
	return &GetCatalogsByIDSharedVariationAttributesByIDParams{

		timeout: timeout,
	}
}

// NewGetCatalogsByIDSharedVariationAttributesByIDParamsWithContext creates a new GetCatalogsByIDSharedVariationAttributesByIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetCatalogsByIDSharedVariationAttributesByIDParamsWithContext(ctx context.Context) *GetCatalogsByIDSharedVariationAttributesByIDParams {
	var ()
	return &GetCatalogsByIDSharedVariationAttributesByIDParams{

		Context: ctx,
	}
}

// NewGetCatalogsByIDSharedVariationAttributesByIDParamsWithHTTPClient creates a new GetCatalogsByIDSharedVariationAttributesByIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetCatalogsByIDSharedVariationAttributesByIDParamsWithHTTPClient(client *http.Client) *GetCatalogsByIDSharedVariationAttributesByIDParams {
	var ()
	return &GetCatalogsByIDSharedVariationAttributesByIDParams{
		HTTPClient: client,
	}
}

/*GetCatalogsByIDSharedVariationAttributesByIDParams contains all the parameters to send to the API endpoint
for the get catalogs by ID shared variation attributes by ID operation typically these are written to a http.Request
*/
type GetCatalogsByIDSharedVariationAttributesByIDParams struct {

	/*CatalogID
	  The id of the catalog.

	*/
	CatalogID string
	/*ID
	  The id of the requested variation attribute.

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get catalogs by ID shared variation attributes by ID params
func (o *GetCatalogsByIDSharedVariationAttributesByIDParams) WithTimeout(timeout time.Duration) *GetCatalogsByIDSharedVariationAttributesByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get catalogs by ID shared variation attributes by ID params
func (o *GetCatalogsByIDSharedVariationAttributesByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get catalogs by ID shared variation attributes by ID params
func (o *GetCatalogsByIDSharedVariationAttributesByIDParams) WithContext(ctx context.Context) *GetCatalogsByIDSharedVariationAttributesByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get catalogs by ID shared variation attributes by ID params
func (o *GetCatalogsByIDSharedVariationAttributesByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get catalogs by ID shared variation attributes by ID params
func (o *GetCatalogsByIDSharedVariationAttributesByIDParams) WithHTTPClient(client *http.Client) *GetCatalogsByIDSharedVariationAttributesByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get catalogs by ID shared variation attributes by ID params
func (o *GetCatalogsByIDSharedVariationAttributesByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCatalogID adds the catalogID to the get catalogs by ID shared variation attributes by ID params
func (o *GetCatalogsByIDSharedVariationAttributesByIDParams) WithCatalogID(catalogID string) *GetCatalogsByIDSharedVariationAttributesByIDParams {
	o.SetCatalogID(catalogID)
	return o
}

// SetCatalogID adds the catalogId to the get catalogs by ID shared variation attributes by ID params
func (o *GetCatalogsByIDSharedVariationAttributesByIDParams) SetCatalogID(catalogID string) {
	o.CatalogID = catalogID
}

// WithID adds the id to the get catalogs by ID shared variation attributes by ID params
func (o *GetCatalogsByIDSharedVariationAttributesByIDParams) WithID(id string) *GetCatalogsByIDSharedVariationAttributesByIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get catalogs by ID shared variation attributes by ID params
func (o *GetCatalogsByIDSharedVariationAttributesByIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetCatalogsByIDSharedVariationAttributesByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param catalog_id
	if err := r.SetPathParam("catalog_id", o.CatalogID); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
