// Code generated by go-swagger; DO NOT EDIT.

package catalogs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/intel352/sfcc-ocapi-client/data_api/models"
)

// NewPutCatalogsByIDSharedProductOptionsByIDParams creates a new PutCatalogsByIDSharedProductOptionsByIDParams object
// with the default values initialized.
func NewPutCatalogsByIDSharedProductOptionsByIDParams() *PutCatalogsByIDSharedProductOptionsByIDParams {
	var ()
	return &PutCatalogsByIDSharedProductOptionsByIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutCatalogsByIDSharedProductOptionsByIDParamsWithTimeout creates a new PutCatalogsByIDSharedProductOptionsByIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutCatalogsByIDSharedProductOptionsByIDParamsWithTimeout(timeout time.Duration) *PutCatalogsByIDSharedProductOptionsByIDParams {
	var ()
	return &PutCatalogsByIDSharedProductOptionsByIDParams{

		timeout: timeout,
	}
}

// NewPutCatalogsByIDSharedProductOptionsByIDParamsWithContext creates a new PutCatalogsByIDSharedProductOptionsByIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutCatalogsByIDSharedProductOptionsByIDParamsWithContext(ctx context.Context) *PutCatalogsByIDSharedProductOptionsByIDParams {
	var ()
	return &PutCatalogsByIDSharedProductOptionsByIDParams{

		Context: ctx,
	}
}

// NewPutCatalogsByIDSharedProductOptionsByIDParamsWithHTTPClient creates a new PutCatalogsByIDSharedProductOptionsByIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutCatalogsByIDSharedProductOptionsByIDParamsWithHTTPClient(client *http.Client) *PutCatalogsByIDSharedProductOptionsByIDParams {
	var ()
	return &PutCatalogsByIDSharedProductOptionsByIDParams{
		HTTPClient: client,
	}
}

/*PutCatalogsByIDSharedProductOptionsByIDParams contains all the parameters to send to the API endpoint
for the put catalogs by ID shared product options by ID operation typically these are written to a http.Request
*/
type PutCatalogsByIDSharedProductOptionsByIDParams struct {

	/*Body*/
	Body *models.ProductOption
	/*CatalogID
	  The id of the catalog.

	*/
	CatalogID string
	/*ID
	  The id of the shared product option.

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put catalogs by ID shared product options by ID params
func (o *PutCatalogsByIDSharedProductOptionsByIDParams) WithTimeout(timeout time.Duration) *PutCatalogsByIDSharedProductOptionsByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put catalogs by ID shared product options by ID params
func (o *PutCatalogsByIDSharedProductOptionsByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put catalogs by ID shared product options by ID params
func (o *PutCatalogsByIDSharedProductOptionsByIDParams) WithContext(ctx context.Context) *PutCatalogsByIDSharedProductOptionsByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put catalogs by ID shared product options by ID params
func (o *PutCatalogsByIDSharedProductOptionsByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put catalogs by ID shared product options by ID params
func (o *PutCatalogsByIDSharedProductOptionsByIDParams) WithHTTPClient(client *http.Client) *PutCatalogsByIDSharedProductOptionsByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put catalogs by ID shared product options by ID params
func (o *PutCatalogsByIDSharedProductOptionsByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the put catalogs by ID shared product options by ID params
func (o *PutCatalogsByIDSharedProductOptionsByIDParams) WithBody(body *models.ProductOption) *PutCatalogsByIDSharedProductOptionsByIDParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the put catalogs by ID shared product options by ID params
func (o *PutCatalogsByIDSharedProductOptionsByIDParams) SetBody(body *models.ProductOption) {
	o.Body = body
}

// WithCatalogID adds the catalogID to the put catalogs by ID shared product options by ID params
func (o *PutCatalogsByIDSharedProductOptionsByIDParams) WithCatalogID(catalogID string) *PutCatalogsByIDSharedProductOptionsByIDParams {
	o.SetCatalogID(catalogID)
	return o
}

// SetCatalogID adds the catalogId to the put catalogs by ID shared product options by ID params
func (o *PutCatalogsByIDSharedProductOptionsByIDParams) SetCatalogID(catalogID string) {
	o.CatalogID = catalogID
}

// WithID adds the id to the put catalogs by ID shared product options by ID params
func (o *PutCatalogsByIDSharedProductOptionsByIDParams) WithID(id string) *PutCatalogsByIDSharedProductOptionsByIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the put catalogs by ID shared product options by ID params
func (o *PutCatalogsByIDSharedProductOptionsByIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PutCatalogsByIDSharedProductOptionsByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param catalog_id
	if err := r.SetPathParam("catalog_id", o.CatalogID); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
