// Code generated by go-swagger; DO NOT EDIT.

package catalogs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/intel352/sfcc-ocapi-client/data_api/models"
)

// PutCatalogsByIDSharedProductOptionsByIDValuesByIDReader is a Reader for the PutCatalogsByIDSharedProductOptionsByIDValuesByID structure.
type PutCatalogsByIDSharedProductOptionsByIDValuesByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutCatalogsByIDSharedProductOptionsByIDValuesByIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 404:
		result := NewPutCatalogsByIDSharedProductOptionsByIDValuesByIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewPutCatalogsByIDSharedProductOptionsByIDValuesByIDDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPutCatalogsByIDSharedProductOptionsByIDValuesByIDNotFound creates a PutCatalogsByIDSharedProductOptionsByIDValuesByIDNotFound with default headers values
func NewPutCatalogsByIDSharedProductOptionsByIDValuesByIDNotFound() *PutCatalogsByIDSharedProductOptionsByIDValuesByIDNotFound {
	return &PutCatalogsByIDSharedProductOptionsByIDValuesByIDNotFound{}
}

/*PutCatalogsByIDSharedProductOptionsByIDValuesByIDNotFound handles this case with default header values.

Indicates the catalog is not found. or Indicates the shared product option is not found.
*/
type PutCatalogsByIDSharedProductOptionsByIDValuesByIDNotFound struct {
}

func (o *PutCatalogsByIDSharedProductOptionsByIDValuesByIDNotFound) Error() string {
	return fmt.Sprintf("[PUT /catalogs/{catalog_id}/shared_product_options/{option_id}/values/{id}][%d] putCatalogsByIdSharedProductOptionsByIdValuesByIdNotFound ", 404)
}

func (o *PutCatalogsByIDSharedProductOptionsByIDValuesByIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPutCatalogsByIDSharedProductOptionsByIDValuesByIDDefault creates a PutCatalogsByIDSharedProductOptionsByIDValuesByIDDefault with default headers values
func NewPutCatalogsByIDSharedProductOptionsByIDValuesByIDDefault(code int) *PutCatalogsByIDSharedProductOptionsByIDValuesByIDDefault {
	return &PutCatalogsByIDSharedProductOptionsByIDValuesByIDDefault{
		_statusCode: code,
	}
}

/*PutCatalogsByIDSharedProductOptionsByIDValuesByIDDefault handles this case with default header values.

PutCatalogsByIDSharedProductOptionsByIDValuesByIDDefault put catalogs by ID shared product options by ID values by ID default
*/
type PutCatalogsByIDSharedProductOptionsByIDValuesByIDDefault struct {
	_statusCode int

	Payload *models.ProductOptionValue
}

// Code gets the status code for the put catalogs by ID shared product options by ID values by ID default response
func (o *PutCatalogsByIDSharedProductOptionsByIDValuesByIDDefault) Code() int {
	return o._statusCode
}

func (o *PutCatalogsByIDSharedProductOptionsByIDValuesByIDDefault) Error() string {
	return fmt.Sprintf("[PUT /catalogs/{catalog_id}/shared_product_options/{option_id}/values/{id}][%d] putCatalogsByIDSharedProductOptionsByIDValuesByID default  %+v", o._statusCode, o.Payload)
}

func (o *PutCatalogsByIDSharedProductOptionsByIDValuesByIDDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProductOptionValue)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
