// Code generated by go-swagger; DO NOT EDIT.

package customers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/intel352/sfcc-ocapi-client/shop_api/models"
)

// PostCustomersByIDProductListsReader is a Reader for the PostCustomersByIDProductLists structure.
type PostCustomersByIDProductListsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostCustomersByIDProductListsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 400:
		result := NewPostCustomersByIDProductListsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewPostCustomersByIDProductListsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewPostCustomersByIDProductListsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPostCustomersByIDProductListsBadRequest creates a PostCustomersByIDProductListsBadRequest with default headers values
func NewPostCustomersByIDProductListsBadRequest() *PostCustomersByIDProductListsBadRequest {
	return &PostCustomersByIDProductListsBadRequest{}
}

/*PostCustomersByIDProductListsBadRequest handles this case with default header values.

Indicates that the id of the given address link does not reference an address
             of the current customer. or Indicates that the customerId URL parameter does not match the verified customer
             represented by the JWT token, not relevant when using OAuth. or Indicates that there was no or an invalid type given for the to be
             created product list.
*/
type PostCustomersByIDProductListsBadRequest struct {
}

func (o *PostCustomersByIDProductListsBadRequest) Error() string {
	return fmt.Sprintf("[POST /customers/{customer_id}/product_lists][%d] postCustomersByIdProductListsBadRequest ", 400)
}

func (o *PostCustomersByIDProductListsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostCustomersByIDProductListsNotFound creates a PostCustomersByIDProductListsNotFound with default headers values
func NewPostCustomersByIDProductListsNotFound() *PostCustomersByIDProductListsNotFound {
	return &PostCustomersByIDProductListsNotFound{}
}

/*PostCustomersByIDProductListsNotFound handles this case with default header values.

Indicates that the customer with the given customer id is unknown for the site.
*/
type PostCustomersByIDProductListsNotFound struct {
}

func (o *PostCustomersByIDProductListsNotFound) Error() string {
	return fmt.Sprintf("[POST /customers/{customer_id}/product_lists][%d] postCustomersByIdProductListsNotFound ", 404)
}

func (o *PostCustomersByIDProductListsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostCustomersByIDProductListsDefault creates a PostCustomersByIDProductListsDefault with default headers values
func NewPostCustomersByIDProductListsDefault(code int) *PostCustomersByIDProductListsDefault {
	return &PostCustomersByIDProductListsDefault{
		_statusCode: code,
	}
}

/*PostCustomersByIDProductListsDefault handles this case with default header values.

PostCustomersByIDProductListsDefault post customers by ID product lists default
*/
type PostCustomersByIDProductListsDefault struct {
	_statusCode int

	Payload *models.CustomerProductList
}

// Code gets the status code for the post customers by ID product lists default response
func (o *PostCustomersByIDProductListsDefault) Code() int {
	return o._statusCode
}

func (o *PostCustomersByIDProductListsDefault) Error() string {
	return fmt.Sprintf("[POST /customers/{customer_id}/product_lists][%d] postCustomersByIDProductLists default  %+v", o._statusCode, o.Payload)
}

func (o *PostCustomersByIDProductListsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CustomerProductList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
