// Code generated by go-swagger; DO NOT EDIT.

package customers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/intel352/sfcc-ocapi-client/shop_api/models"
)

// PostCustomersReader is a Reader for the PostCustomers structure.
type PostCustomersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostCustomersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 400:
		result := NewPostCustomersBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewPostCustomersDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPostCustomersBadRequest creates a PostCustomersBadRequest with default headers values
func NewPostCustomersBadRequest() *PostCustomersBadRequest {
	return &PostCustomersBadRequest{}
}

/*PostCustomersBadRequest handles this case with default header values.

Indicates that the resource is called with JWT token
             representing a registered customer. or Indicates that request document does not contain email. or Indicates that request document does not contain last_name. or Indicates that request document does not contain login. or Indicates that the given login is already used. or Indicates that login doesn't match acceptance criteria. or Indicates that password doesn't match acceptance criteria. or Indicates that password was not provided in JWT scenario.
*/
type PostCustomersBadRequest struct {
}

func (o *PostCustomersBadRequest) Error() string {
	return fmt.Sprintf("[POST /customers][%d] postCustomersBadRequest ", 400)
}

func (o *PostCustomersBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostCustomersDefault creates a PostCustomersDefault with default headers values
func NewPostCustomersDefault(code int) *PostCustomersDefault {
	return &PostCustomersDefault{
		_statusCode: code,
	}
}

/*PostCustomersDefault handles this case with default header values.

PostCustomersDefault post customers default
*/
type PostCustomersDefault struct {
	_statusCode int

	Payload *models.Customer
}

// Code gets the status code for the post customers default response
func (o *PostCustomersDefault) Code() int {
	return o._statusCode
}

func (o *PostCustomersDefault) Error() string {
	return fmt.Sprintf("[POST /customers][%d] postCustomers default  %+v", o._statusCode, o.Payload)
}

func (o *PostCustomersDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Customer)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
