// Code generated by go-swagger; DO NOT EDIT.

package custom_objects

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteCustomObjectsByIDByIDParams creates a new DeleteCustomObjectsByIDByIDParams object
// with the default values initialized.
func NewDeleteCustomObjectsByIDByIDParams() *DeleteCustomObjectsByIDByIDParams {
	var ()
	return &DeleteCustomObjectsByIDByIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteCustomObjectsByIDByIDParamsWithTimeout creates a new DeleteCustomObjectsByIDByIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteCustomObjectsByIDByIDParamsWithTimeout(timeout time.Duration) *DeleteCustomObjectsByIDByIDParams {
	var ()
	return &DeleteCustomObjectsByIDByIDParams{

		timeout: timeout,
	}
}

// NewDeleteCustomObjectsByIDByIDParamsWithContext creates a new DeleteCustomObjectsByIDByIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteCustomObjectsByIDByIDParamsWithContext(ctx context.Context) *DeleteCustomObjectsByIDByIDParams {
	var ()
	return &DeleteCustomObjectsByIDByIDParams{

		Context: ctx,
	}
}

// NewDeleteCustomObjectsByIDByIDParamsWithHTTPClient creates a new DeleteCustomObjectsByIDByIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteCustomObjectsByIDByIDParamsWithHTTPClient(client *http.Client) *DeleteCustomObjectsByIDByIDParams {
	var ()
	return &DeleteCustomObjectsByIDByIDParams{
		HTTPClient: client,
	}
}

/*DeleteCustomObjectsByIDByIDParams contains all the parameters to send to the API endpoint
for the delete custom objects by ID by ID operation typically these are written to a http.Request
*/
type DeleteCustomObjectsByIDByIDParams struct {

	/*Key
	  the key attribute value of the Custom Object

	*/
	Key string
	/*ObjectType
	  the ID of the object type

	*/
	ObjectType string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete custom objects by ID by ID params
func (o *DeleteCustomObjectsByIDByIDParams) WithTimeout(timeout time.Duration) *DeleteCustomObjectsByIDByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete custom objects by ID by ID params
func (o *DeleteCustomObjectsByIDByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete custom objects by ID by ID params
func (o *DeleteCustomObjectsByIDByIDParams) WithContext(ctx context.Context) *DeleteCustomObjectsByIDByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete custom objects by ID by ID params
func (o *DeleteCustomObjectsByIDByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete custom objects by ID by ID params
func (o *DeleteCustomObjectsByIDByIDParams) WithHTTPClient(client *http.Client) *DeleteCustomObjectsByIDByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete custom objects by ID by ID params
func (o *DeleteCustomObjectsByIDByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithKey adds the key to the delete custom objects by ID by ID params
func (o *DeleteCustomObjectsByIDByIDParams) WithKey(key string) *DeleteCustomObjectsByIDByIDParams {
	o.SetKey(key)
	return o
}

// SetKey adds the key to the delete custom objects by ID by ID params
func (o *DeleteCustomObjectsByIDByIDParams) SetKey(key string) {
	o.Key = key
}

// WithObjectType adds the objectType to the delete custom objects by ID by ID params
func (o *DeleteCustomObjectsByIDByIDParams) WithObjectType(objectType string) *DeleteCustomObjectsByIDByIDParams {
	o.SetObjectType(objectType)
	return o
}

// SetObjectType adds the objectType to the delete custom objects by ID by ID params
func (o *DeleteCustomObjectsByIDByIDParams) SetObjectType(objectType string) {
	o.ObjectType = objectType
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteCustomObjectsByIDByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param key
	if err := r.SetPathParam("key", o.Key); err != nil {
		return err
	}

	// path param object_type
	if err := r.SetPathParam("object_type", o.ObjectType); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
