// Code generated by go-swagger; DO NOT EDIT.

package promotions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/intel352/sfcc-ocapi-client/shop_api/models"
)

// GetPromotionsReader is a Reader for the GetPromotions structure.
type GetPromotionsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPromotionsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 400:
		result := NewGetPromotionsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewGetPromotionsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetPromotionsBadRequest creates a GetPromotionsBadRequest with default headers values
func NewGetPromotionsBadRequest() *GetPromotionsBadRequest {
	return &GetPromotionsBadRequest{}
}

/*GetPromotionsBadRequest handles this case with default header values.

Thrown when a start date, but no end date was given or Thrown when an end date but no start date was given or Thrown when the given end date is before the given start date
*/
type GetPromotionsBadRequest struct {
}

func (o *GetPromotionsBadRequest) Error() string {
	return fmt.Sprintf("[GET /promotions][%d] getPromotionsBadRequest ", 400)
}

func (o *GetPromotionsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetPromotionsDefault creates a GetPromotionsDefault with default headers values
func NewGetPromotionsDefault(code int) *GetPromotionsDefault {
	return &GetPromotionsDefault{
		_statusCode: code,
	}
}

/*GetPromotionsDefault handles this case with default header values.

GetPromotionsDefault get promotions default
*/
type GetPromotionsDefault struct {
	_statusCode int

	Payload *models.PromotionResult
}

// Code gets the status code for the get promotions default response
func (o *GetPromotionsDefault) Code() int {
	return o._statusCode
}

func (o *GetPromotionsDefault) Error() string {
	return fmt.Sprintf("[GET /promotions][%d] getPromotions default  %+v", o._statusCode, o.Payload)
}

func (o *GetPromotionsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PromotionResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
