// Code generated by go-swagger; DO NOT EDIT.

package customer_lists

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/intel352/sfcc-ocapi-client/data_api/models"
)

// PostCustomerListsByIDCustomersByIDAddressesReader is a Reader for the PostCustomerListsByIDCustomersByIDAddresses structure.
type PostCustomerListsByIDCustomersByIDAddressesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostCustomerListsByIDCustomersByIDAddressesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 400:
		result := NewPostCustomerListsByIDCustomersByIDAddressesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewPostCustomerListsByIDCustomersByIDAddressesNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewPostCustomerListsByIDCustomersByIDAddressesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPostCustomerListsByIDCustomersByIDAddressesBadRequest creates a PostCustomerListsByIDCustomersByIDAddressesBadRequest with default headers values
func NewPostCustomerListsByIDCustomersByIDAddressesBadRequest() *PostCustomerListsByIDCustomersByIDAddressesBadRequest {
	return &PostCustomerListsByIDCustomersByIDAddressesBadRequest{}
}

/*PostCustomerListsByIDCustomersByIDAddressesBadRequest handles this case with default header values.

If the address id is null or empty. or If the address id is already in use.
*/
type PostCustomerListsByIDCustomersByIDAddressesBadRequest struct {
}

func (o *PostCustomerListsByIDCustomersByIDAddressesBadRequest) Error() string {
	return fmt.Sprintf("[POST /customer_lists/{list_id}/customers/{customer_no}/addresses][%d] postCustomerListsByIdCustomersByIdAddressesBadRequest ", 400)
}

func (o *PostCustomerListsByIDCustomersByIDAddressesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostCustomerListsByIDCustomersByIDAddressesNotFound creates a PostCustomerListsByIDCustomersByIDAddressesNotFound with default headers values
func NewPostCustomerListsByIDCustomersByIDAddressesNotFound() *PostCustomerListsByIDCustomersByIDAddressesNotFound {
	return &PostCustomerListsByIDCustomersByIDAddressesNotFound{}
}

/*PostCustomerListsByIDCustomersByIDAddressesNotFound handles this case with default header values.

Indicates that the customer with the given customer number is unknown. or Indicates that the customer list with the given customer list id is unknown.
*/
type PostCustomerListsByIDCustomersByIDAddressesNotFound struct {
}

func (o *PostCustomerListsByIDCustomersByIDAddressesNotFound) Error() string {
	return fmt.Sprintf("[POST /customer_lists/{list_id}/customers/{customer_no}/addresses][%d] postCustomerListsByIdCustomersByIdAddressesNotFound ", 404)
}

func (o *PostCustomerListsByIDCustomersByIDAddressesNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostCustomerListsByIDCustomersByIDAddressesDefault creates a PostCustomerListsByIDCustomersByIDAddressesDefault with default headers values
func NewPostCustomerListsByIDCustomersByIDAddressesDefault(code int) *PostCustomerListsByIDCustomersByIDAddressesDefault {
	return &PostCustomerListsByIDCustomersByIDAddressesDefault{
		_statusCode: code,
	}
}

/*PostCustomerListsByIDCustomersByIDAddressesDefault handles this case with default header values.

PostCustomerListsByIDCustomersByIDAddressesDefault post customer lists by ID customers by ID addresses default
*/
type PostCustomerListsByIDCustomersByIDAddressesDefault struct {
	_statusCode int

	Payload *models.CustomerAddress
}

// Code gets the status code for the post customer lists by ID customers by ID addresses default response
func (o *PostCustomerListsByIDCustomersByIDAddressesDefault) Code() int {
	return o._statusCode
}

func (o *PostCustomerListsByIDCustomersByIDAddressesDefault) Error() string {
	return fmt.Sprintf("[POST /customer_lists/{list_id}/customers/{customer_no}/addresses][%d] postCustomerListsByIDCustomersByIDAddresses default  %+v", o._statusCode, o.Payload)
}

func (o *PostCustomerListsByIDCustomersByIDAddressesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CustomerAddress)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
