// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// VersionDescription Description object for a version in an API.
// swagger:model version_description
type VersionDescription struct {

	// HTTP link to the swagger document for the API and the version
	Link string `json:"link,omitempty"`

	// Version name.
	Name string `json:"name,omitempty"`

	// Version status.
	Status string `json:"status,omitempty"`
}

// Validate validates this version description
func (m *VersionDescription) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *VersionDescription) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VersionDescription) UnmarshalBinary(b []byte) error {
	var res VersionDescription
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
