// Code generated by go-swagger; DO NOT EDIT.

package content

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/intel352/sfcc-ocapi-client/shop_api/models"
)

// GetContentByIDReader is a Reader for the GetContentByID structure.
type GetContentByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetContentByIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {

	result := NewGetContentByIDDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result

}

// NewGetContentByIDDefault creates a GetContentByIDDefault with default headers values
func NewGetContentByIDDefault(code int) *GetContentByIDDefault {
	return &GetContentByIDDefault{
		_statusCode: code,
	}
}

/*GetContentByIDDefault handles this case with default header values.

GetContentByIDDefault get content by ID default
*/
type GetContentByIDDefault struct {
	_statusCode int

	Payload *models.Content
}

// Code gets the status code for the get content by ID default response
func (o *GetContentByIDDefault) Code() int {
	return o._statusCode
}

func (o *GetContentByIDDefault) Error() string {
	return fmt.Sprintf("[GET /content/{id}][%d] getContentByID default  %+v", o._statusCode, o.Payload)
}

func (o *GetContentByIDDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Content)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
