// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetProductsByIDVariationsByIDParams creates a new GetProductsByIDVariationsByIDParams object
// with the default values initialized.
func NewGetProductsByIDVariationsByIDParams() *GetProductsByIDVariationsByIDParams {
	var ()
	return &GetProductsByIDVariationsByIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetProductsByIDVariationsByIDParamsWithTimeout creates a new GetProductsByIDVariationsByIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetProductsByIDVariationsByIDParamsWithTimeout(timeout time.Duration) *GetProductsByIDVariationsByIDParams {
	var ()
	return &GetProductsByIDVariationsByIDParams{

		timeout: timeout,
	}
}

// NewGetProductsByIDVariationsByIDParamsWithContext creates a new GetProductsByIDVariationsByIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetProductsByIDVariationsByIDParamsWithContext(ctx context.Context) *GetProductsByIDVariationsByIDParams {
	var ()
	return &GetProductsByIDVariationsByIDParams{

		Context: ctx,
	}
}

// NewGetProductsByIDVariationsByIDParamsWithHTTPClient creates a new GetProductsByIDVariationsByIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetProductsByIDVariationsByIDParamsWithHTTPClient(client *http.Client) *GetProductsByIDVariationsByIDParams {
	var ()
	return &GetProductsByIDVariationsByIDParams{
		HTTPClient: client,
	}
}

/*GetProductsByIDVariationsByIDParams contains all the parameters to send to the API endpoint
for the get products by ID variations by ID operation typically these are written to a http.Request
*/
type GetProductsByIDVariationsByIDParams struct {

	/*Expand*/
	Expand []string
	/*ID
	  The id of the variation product.

	*/
	ID string
	/*MasterProductID
	  The id of the master product that contains the variation.

	*/
	MasterProductID string
	/*SiteID*/
	SiteID *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get products by ID variations by ID params
func (o *GetProductsByIDVariationsByIDParams) WithTimeout(timeout time.Duration) *GetProductsByIDVariationsByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get products by ID variations by ID params
func (o *GetProductsByIDVariationsByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get products by ID variations by ID params
func (o *GetProductsByIDVariationsByIDParams) WithContext(ctx context.Context) *GetProductsByIDVariationsByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get products by ID variations by ID params
func (o *GetProductsByIDVariationsByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get products by ID variations by ID params
func (o *GetProductsByIDVariationsByIDParams) WithHTTPClient(client *http.Client) *GetProductsByIDVariationsByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get products by ID variations by ID params
func (o *GetProductsByIDVariationsByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithExpand adds the expand to the get products by ID variations by ID params
func (o *GetProductsByIDVariationsByIDParams) WithExpand(expand []string) *GetProductsByIDVariationsByIDParams {
	o.SetExpand(expand)
	return o
}

// SetExpand adds the expand to the get products by ID variations by ID params
func (o *GetProductsByIDVariationsByIDParams) SetExpand(expand []string) {
	o.Expand = expand
}

// WithID adds the id to the get products by ID variations by ID params
func (o *GetProductsByIDVariationsByIDParams) WithID(id string) *GetProductsByIDVariationsByIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get products by ID variations by ID params
func (o *GetProductsByIDVariationsByIDParams) SetID(id string) {
	o.ID = id
}

// WithMasterProductID adds the masterProductID to the get products by ID variations by ID params
func (o *GetProductsByIDVariationsByIDParams) WithMasterProductID(masterProductID string) *GetProductsByIDVariationsByIDParams {
	o.SetMasterProductID(masterProductID)
	return o
}

// SetMasterProductID adds the masterProductId to the get products by ID variations by ID params
func (o *GetProductsByIDVariationsByIDParams) SetMasterProductID(masterProductID string) {
	o.MasterProductID = masterProductID
}

// WithSiteID adds the siteID to the get products by ID variations by ID params
func (o *GetProductsByIDVariationsByIDParams) WithSiteID(siteID *string) *GetProductsByIDVariationsByIDParams {
	o.SetSiteID(siteID)
	return o
}

// SetSiteID adds the siteId to the get products by ID variations by ID params
func (o *GetProductsByIDVariationsByIDParams) SetSiteID(siteID *string) {
	o.SiteID = siteID
}

// WriteToRequest writes these params to a swagger request
func (o *GetProductsByIDVariationsByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	valuesExpand := o.Expand

	joinedExpand := swag.JoinByFormat(valuesExpand, "")
	// query array param expand
	if err := r.SetQueryParam("expand", joinedExpand...); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	// path param master_product_id
	if err := r.SetPathParam("master_product_id", o.MasterProductID); err != nil {
		return err
	}

	if o.SiteID != nil {

		// query param site_id
		var qrSiteID string
		if o.SiteID != nil {
			qrSiteID = *o.SiteID
		}
		qSiteID := qrSiteID
		if qSiteID != "" {
			if err := r.SetQueryParam("site_id", qSiteID); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
