// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// DiscountRequest Document representing a discount to be applied to a custom price adjustment. The properties
// swagger:model discount_request
type DiscountRequest struct {

	// The type of discount.
	// Required: true
	// Enum: [percentage fixed_price amount]
	Type *string `json:"type"`

	// The amount of the discount.
	// Required: true
	Value *float64 `json:"value"`
}

// Validate validates this discount request
func (m *DiscountRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateValue(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var discountRequestTypeTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["percentage","fixed_price","amount"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		discountRequestTypeTypePropEnum = append(discountRequestTypeTypePropEnum, v)
	}
}

const (

	// DiscountRequestTypePercentage captures enum value "percentage"
	DiscountRequestTypePercentage string = "percentage"

	// DiscountRequestTypeFixedPrice captures enum value "fixed_price"
	DiscountRequestTypeFixedPrice string = "fixed_price"

	// DiscountRequestTypeAmount captures enum value "amount"
	DiscountRequestTypeAmount string = "amount"
)

// prop value enum
func (m *DiscountRequest) validateTypeEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, discountRequestTypeTypePropEnum); err != nil {
		return err
	}
	return nil
}

func (m *DiscountRequest) validateType(formats strfmt.Registry) error {

	if err := validate.Required("type", "body", m.Type); err != nil {
		return err
	}

	// value enum
	if err := m.validateTypeEnum("type", "body", *m.Type); err != nil {
		return err
	}

	return nil
}

func (m *DiscountRequest) validateValue(formats strfmt.Registry) error {

	if err := validate.Required("value", "body", m.Value); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *DiscountRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DiscountRequest) UnmarshalBinary(b []byte) error {
	var res DiscountRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
