// Code generated by go-swagger; DO NOT EDIT.

package system_object_definitions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/intel352/sfcc-ocapi-client/data_api/models"
)

// GetSystemObjectDefinitionsByIDReader is a Reader for the GetSystemObjectDefinitionsByID structure.
type GetSystemObjectDefinitionsByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetSystemObjectDefinitionsByIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 404:
		result := NewGetSystemObjectDefinitionsByIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewGetSystemObjectDefinitionsByIDDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetSystemObjectDefinitionsByIDNotFound creates a GetSystemObjectDefinitionsByIDNotFound with default headers values
func NewGetSystemObjectDefinitionsByIDNotFound() *GetSystemObjectDefinitionsByIDNotFound {
	return &GetSystemObjectDefinitionsByIDNotFound{}
}

/*GetSystemObjectDefinitionsByIDNotFound handles this case with default header values.

Thrown in case the system object does not exist matching the given objectType
*/
type GetSystemObjectDefinitionsByIDNotFound struct {
}

func (o *GetSystemObjectDefinitionsByIDNotFound) Error() string {
	return fmt.Sprintf("[GET /system_object_definitions/{object_type}][%d] getSystemObjectDefinitionsByIdNotFound ", 404)
}

func (o *GetSystemObjectDefinitionsByIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetSystemObjectDefinitionsByIDDefault creates a GetSystemObjectDefinitionsByIDDefault with default headers values
func NewGetSystemObjectDefinitionsByIDDefault(code int) *GetSystemObjectDefinitionsByIDDefault {
	return &GetSystemObjectDefinitionsByIDDefault{
		_statusCode: code,
	}
}

/*GetSystemObjectDefinitionsByIDDefault handles this case with default header values.

GetSystemObjectDefinitionsByIDDefault get system object definitions by ID default
*/
type GetSystemObjectDefinitionsByIDDefault struct {
	_statusCode int

	Payload *models.ObjectTypeDefinition
}

// Code gets the status code for the get system object definitions by ID default response
func (o *GetSystemObjectDefinitionsByIDDefault) Code() int {
	return o._statusCode
}

func (o *GetSystemObjectDefinitionsByIDDefault) Error() string {
	return fmt.Sprintf("[GET /system_object_definitions/{object_type}][%d] getSystemObjectDefinitionsByID default  %+v", o._statusCode, o.Payload)
}

func (o *GetSystemObjectDefinitionsByIDDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ObjectTypeDefinition)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
