// Code generated by go-swagger; DO NOT EDIT.

package system_object_definitions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/intel352/sfcc-ocapi-client/data_api/models"
)

// NewPostSystemObjectDefinitionsByIDAttributeDefinitionSearchParams creates a new PostSystemObjectDefinitionsByIDAttributeDefinitionSearchParams object
// with the default values initialized.
func NewPostSystemObjectDefinitionsByIDAttributeDefinitionSearchParams() *PostSystemObjectDefinitionsByIDAttributeDefinitionSearchParams {
	var ()
	return &PostSystemObjectDefinitionsByIDAttributeDefinitionSearchParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostSystemObjectDefinitionsByIDAttributeDefinitionSearchParamsWithTimeout creates a new PostSystemObjectDefinitionsByIDAttributeDefinitionSearchParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostSystemObjectDefinitionsByIDAttributeDefinitionSearchParamsWithTimeout(timeout time.Duration) *PostSystemObjectDefinitionsByIDAttributeDefinitionSearchParams {
	var ()
	return &PostSystemObjectDefinitionsByIDAttributeDefinitionSearchParams{

		timeout: timeout,
	}
}

// NewPostSystemObjectDefinitionsByIDAttributeDefinitionSearchParamsWithContext creates a new PostSystemObjectDefinitionsByIDAttributeDefinitionSearchParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostSystemObjectDefinitionsByIDAttributeDefinitionSearchParamsWithContext(ctx context.Context) *PostSystemObjectDefinitionsByIDAttributeDefinitionSearchParams {
	var ()
	return &PostSystemObjectDefinitionsByIDAttributeDefinitionSearchParams{

		Context: ctx,
	}
}

// NewPostSystemObjectDefinitionsByIDAttributeDefinitionSearchParamsWithHTTPClient creates a new PostSystemObjectDefinitionsByIDAttributeDefinitionSearchParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostSystemObjectDefinitionsByIDAttributeDefinitionSearchParamsWithHTTPClient(client *http.Client) *PostSystemObjectDefinitionsByIDAttributeDefinitionSearchParams {
	var ()
	return &PostSystemObjectDefinitionsByIDAttributeDefinitionSearchParams{
		HTTPClient: client,
	}
}

/*PostSystemObjectDefinitionsByIDAttributeDefinitionSearchParams contains all the parameters to send to the API endpoint
for the post system object definitions by ID attribute definition search operation typically these are written to a http.Request
*/
type PostSystemObjectDefinitionsByIDAttributeDefinitionSearchParams struct {

	/*Body*/
	Body *models.SearchRequest
	/*ObjectType
	  The object type id that contains these definitions

	*/
	ObjectType string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post system object definitions by ID attribute definition search params
func (o *PostSystemObjectDefinitionsByIDAttributeDefinitionSearchParams) WithTimeout(timeout time.Duration) *PostSystemObjectDefinitionsByIDAttributeDefinitionSearchParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post system object definitions by ID attribute definition search params
func (o *PostSystemObjectDefinitionsByIDAttributeDefinitionSearchParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post system object definitions by ID attribute definition search params
func (o *PostSystemObjectDefinitionsByIDAttributeDefinitionSearchParams) WithContext(ctx context.Context) *PostSystemObjectDefinitionsByIDAttributeDefinitionSearchParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post system object definitions by ID attribute definition search params
func (o *PostSystemObjectDefinitionsByIDAttributeDefinitionSearchParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post system object definitions by ID attribute definition search params
func (o *PostSystemObjectDefinitionsByIDAttributeDefinitionSearchParams) WithHTTPClient(client *http.Client) *PostSystemObjectDefinitionsByIDAttributeDefinitionSearchParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post system object definitions by ID attribute definition search params
func (o *PostSystemObjectDefinitionsByIDAttributeDefinitionSearchParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post system object definitions by ID attribute definition search params
func (o *PostSystemObjectDefinitionsByIDAttributeDefinitionSearchParams) WithBody(body *models.SearchRequest) *PostSystemObjectDefinitionsByIDAttributeDefinitionSearchParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post system object definitions by ID attribute definition search params
func (o *PostSystemObjectDefinitionsByIDAttributeDefinitionSearchParams) SetBody(body *models.SearchRequest) {
	o.Body = body
}

// WithObjectType adds the objectType to the post system object definitions by ID attribute definition search params
func (o *PostSystemObjectDefinitionsByIDAttributeDefinitionSearchParams) WithObjectType(objectType string) *PostSystemObjectDefinitionsByIDAttributeDefinitionSearchParams {
	o.SetObjectType(objectType)
	return o
}

// SetObjectType adds the objectType to the post system object definitions by ID attribute definition search params
func (o *PostSystemObjectDefinitionsByIDAttributeDefinitionSearchParams) SetObjectType(objectType string) {
	o.ObjectType = objectType
}

// WriteToRequest writes these params to a swagger request
func (o *PostSystemObjectDefinitionsByIDAttributeDefinitionSearchParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param object_type
	if err := r.SetPathParam("object_type", o.ObjectType); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
