// Code generated by go-swagger; DO NOT EDIT.

package system_object_definitions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/intel352/sfcc-ocapi-client/data_api/models"
)

// NewPutSystemObjectDefinitionsByIDAttributeDefinitionsByIDParams creates a new PutSystemObjectDefinitionsByIDAttributeDefinitionsByIDParams object
// with the default values initialized.
func NewPutSystemObjectDefinitionsByIDAttributeDefinitionsByIDParams() *PutSystemObjectDefinitionsByIDAttributeDefinitionsByIDParams {
	var ()
	return &PutSystemObjectDefinitionsByIDAttributeDefinitionsByIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutSystemObjectDefinitionsByIDAttributeDefinitionsByIDParamsWithTimeout creates a new PutSystemObjectDefinitionsByIDAttributeDefinitionsByIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutSystemObjectDefinitionsByIDAttributeDefinitionsByIDParamsWithTimeout(timeout time.Duration) *PutSystemObjectDefinitionsByIDAttributeDefinitionsByIDParams {
	var ()
	return &PutSystemObjectDefinitionsByIDAttributeDefinitionsByIDParams{

		timeout: timeout,
	}
}

// NewPutSystemObjectDefinitionsByIDAttributeDefinitionsByIDParamsWithContext creates a new PutSystemObjectDefinitionsByIDAttributeDefinitionsByIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutSystemObjectDefinitionsByIDAttributeDefinitionsByIDParamsWithContext(ctx context.Context) *PutSystemObjectDefinitionsByIDAttributeDefinitionsByIDParams {
	var ()
	return &PutSystemObjectDefinitionsByIDAttributeDefinitionsByIDParams{

		Context: ctx,
	}
}

// NewPutSystemObjectDefinitionsByIDAttributeDefinitionsByIDParamsWithHTTPClient creates a new PutSystemObjectDefinitionsByIDAttributeDefinitionsByIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutSystemObjectDefinitionsByIDAttributeDefinitionsByIDParamsWithHTTPClient(client *http.Client) *PutSystemObjectDefinitionsByIDAttributeDefinitionsByIDParams {
	var ()
	return &PutSystemObjectDefinitionsByIDAttributeDefinitionsByIDParams{
		HTTPClient: client,
	}
}

/*PutSystemObjectDefinitionsByIDAttributeDefinitionsByIDParams contains all the parameters to send to the API endpoint
for the put system object definitions by ID attribute definitions by ID operation typically these are written to a http.Request
*/
type PutSystemObjectDefinitionsByIDAttributeDefinitionsByIDParams struct {

	/*Body*/
	Body *models.ObjectAttributeDefinition
	/*ID
	  The id of the attribute definition to create.

	*/
	ID string
	/*ObjectType
	  The metadata object that contains these definitions

	*/
	ObjectType string
	/*XDwValidateExisting*/
	XDwValidateExisting *bool

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put system object definitions by ID attribute definitions by ID params
func (o *PutSystemObjectDefinitionsByIDAttributeDefinitionsByIDParams) WithTimeout(timeout time.Duration) *PutSystemObjectDefinitionsByIDAttributeDefinitionsByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put system object definitions by ID attribute definitions by ID params
func (o *PutSystemObjectDefinitionsByIDAttributeDefinitionsByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put system object definitions by ID attribute definitions by ID params
func (o *PutSystemObjectDefinitionsByIDAttributeDefinitionsByIDParams) WithContext(ctx context.Context) *PutSystemObjectDefinitionsByIDAttributeDefinitionsByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put system object definitions by ID attribute definitions by ID params
func (o *PutSystemObjectDefinitionsByIDAttributeDefinitionsByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put system object definitions by ID attribute definitions by ID params
func (o *PutSystemObjectDefinitionsByIDAttributeDefinitionsByIDParams) WithHTTPClient(client *http.Client) *PutSystemObjectDefinitionsByIDAttributeDefinitionsByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put system object definitions by ID attribute definitions by ID params
func (o *PutSystemObjectDefinitionsByIDAttributeDefinitionsByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the put system object definitions by ID attribute definitions by ID params
func (o *PutSystemObjectDefinitionsByIDAttributeDefinitionsByIDParams) WithBody(body *models.ObjectAttributeDefinition) *PutSystemObjectDefinitionsByIDAttributeDefinitionsByIDParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the put system object definitions by ID attribute definitions by ID params
func (o *PutSystemObjectDefinitionsByIDAttributeDefinitionsByIDParams) SetBody(body *models.ObjectAttributeDefinition) {
	o.Body = body
}

// WithID adds the id to the put system object definitions by ID attribute definitions by ID params
func (o *PutSystemObjectDefinitionsByIDAttributeDefinitionsByIDParams) WithID(id string) *PutSystemObjectDefinitionsByIDAttributeDefinitionsByIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the put system object definitions by ID attribute definitions by ID params
func (o *PutSystemObjectDefinitionsByIDAttributeDefinitionsByIDParams) SetID(id string) {
	o.ID = id
}

// WithObjectType adds the objectType to the put system object definitions by ID attribute definitions by ID params
func (o *PutSystemObjectDefinitionsByIDAttributeDefinitionsByIDParams) WithObjectType(objectType string) *PutSystemObjectDefinitionsByIDAttributeDefinitionsByIDParams {
	o.SetObjectType(objectType)
	return o
}

// SetObjectType adds the objectType to the put system object definitions by ID attribute definitions by ID params
func (o *PutSystemObjectDefinitionsByIDAttributeDefinitionsByIDParams) SetObjectType(objectType string) {
	o.ObjectType = objectType
}

// WithXDwValidateExisting adds the xDwValidateExisting to the put system object definitions by ID attribute definitions by ID params
func (o *PutSystemObjectDefinitionsByIDAttributeDefinitionsByIDParams) WithXDwValidateExisting(xDwValidateExisting *bool) *PutSystemObjectDefinitionsByIDAttributeDefinitionsByIDParams {
	o.SetXDwValidateExisting(xDwValidateExisting)
	return o
}

// SetXDwValidateExisting adds the xDwValidateExisting to the put system object definitions by ID attribute definitions by ID params
func (o *PutSystemObjectDefinitionsByIDAttributeDefinitionsByIDParams) SetXDwValidateExisting(xDwValidateExisting *bool) {
	o.XDwValidateExisting = xDwValidateExisting
}

// WriteToRequest writes these params to a swagger request
func (o *PutSystemObjectDefinitionsByIDAttributeDefinitionsByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	// path param object_type
	if err := r.SetPathParam("object_type", o.ObjectType); err != nil {
		return err
	}

	if o.XDwValidateExisting != nil {

		// header param x-dw-validate-existing
		if err := r.SetHeaderParam("x-dw-validate-existing", swag.FormatBool(*o.XDwValidateExisting)); err != nil {
			return err
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
